### ISSUE TITLE
create clingen report

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#1]
for @mellybelly

**Comment by cmungall** [comment]
This is a prototype for https://github.com/monarch-initiative/monarch-app/issues/834

**Comment by cmungall** [comment]
https://github.com/monarch-initiative/monarch-disease-ontology/tree/master/reports/genes

Still multiple known issues. Isn't resolving to most specific class. Many links do not work. Need to show more. EtC

**Comment by cmungall** [comment]
The NER I'm using isn't good at Danon vs Dannon e.g. https://github.com/monarch-initiative/monarch-disease-ontology/blob/master/reports/genes/LAMP2.md#dannon-disease

**Comment by mellybelly** [comment]
@tudorgroza can advise?

**Comment by tudorgroza** [comment]
Not sure I understand what is the task - is it disease concept recognition using DO / MeSH? If yes - we can try the HPO CR and see if it is better.

**Comment by cmungall** [comment]
The specific missing match was due to a presumed typo on one side or the other. I'm not matching Danon to Dannon

**Comment by mellybelly** [comment]
Would be great to see all synonyms and labels in each equivalency set. 

Also, for documentation, lets make figures for some of the diseases described for LMNA, MYH7, CAV3, and CDKL5

**Comment by cmungall** [comment]
Try these:

 * https://github.com/monarch-initiative/monarch-disease-ontology/blob/master/reports/genes/LMNA.md
 * https://github.com/monarch-initiative/monarch-disease-ontology/blob/master/reports/genes/MYH7.md
 * https://github.com/monarch-initiative/monarch-disease-ontology/blob/master/reports/genes/MYH7.md
 * https://github.com/monarch-initiative/monarch-disease-ontology/blob/master/reports/genes/CDKL5.md

**Comment by nicolevasilevsky** [comment]
can this be closed?
