### ISSUE TITLE
fix grouping classes

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#10]
_From @nlwashington on March 6, 2015 17:50_

i've been looking through our the ontology, i've found some issues.

many of the classes in the merged.obo are missing seemingly pedantic grouping classes.

for example,

id: OMIM:614480
name: Hypertriglyceridemia, Transient Infantile
is_a: DOID:630 ! genetic disease

id: OMIM:145750
name: familial hypertriglyceridemia
def: "A lipid metabolism disorder characterized by elevated triglyceride levels as a result of excess hepatic production of VLDL or heterozygous LPL deficiency." [url:http://en.wikipedia.org/wiki/Familial_hypertriglyceridemia]
comment: OMIM mapping confirmed by DO. [SN].
synonym: "Pure hyperglyceridemia" EXACT []
xref: DOID:0050527
is_a: DOID:3146 ! lipid metabolism disorder
is_a: DOID:630 ! genetic disease

are not related to one another except for both being genetic diseases. why isn't the former also a lipid metabolism disorder? or even better, why aren't they both classified as "hypertriglyceridemia"? that seems like a natural grouping class.

another

id: OMIM:606170
name: Genitopatellar Syndrome
is_a: DOID:630 ! genetic disease

in the text there is the description, "The SBBYS variant of Ohdo syndrome (603736) is an allelic disorder with overlapping features."

but it is also not classified:
[Term]
id: OMIM:603736
name: Ohdo Syndrome, Sbbys Variant
is_a: DOID:630 ! genetic disease

so i'd think they would be grouped together in some way.

when i just browse the ontology in protege, if you look under "genetic disease" there are many things that are siblings, but have nearly identical names, suggesting they should be subclasses of a more general disease, but are instead just a big fat flat list. some examples pulled only from A:

Acyl-coa Dehydrogenase \* Deficiency Of
Adams-oliver Syndrome
Adrenal Hyperplasia, Congenital
Arthrogryposis \* (only 3 of the 6 are classified as subtypes)
Atrial Fibrillation (only 4 of 8 are classified as subtypes)
Atrial Septal Defect (only 4 of 8 are classified as subtypes) ...
in fact, 2257 of the omim diseases in the merged file can't be classified into any upper-level grouping class at all except for a plain "genetic disease", which isn't too helpful.

migrated from https://github.com/monarch-initiative/disease-miner/issues/8

_Copied from original issue: monarch-initiative/human-disease-ontology#6_

**Comment by cmungall** [comment]
_From @pnrobinson on March 7, 2015 5:39_

Hi everybody,

please note that OMIM's phenotype series while extremely useful do not attempt to be a full ontology. Orphanet's ORDO is an ontology of rare diseases that does cover this, and I would very much support us supporting and using ORDO, for the simple reason that we will be able to influence its development and because it is even now an extremely useful resource (it is of course still a WIP -- work in progress). I am a coauthor on a submitted manuscript on ORDO, and I am a coapplicant on an eRARE application with Ana Rath, who is leading ORDO development, and I have a very good feeling that ORDO will develop into something that will be really good for us.
-Peter


Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor in the Bioinformatics Division of the Department of Mathematics and Computer Science of the Freie Universit�t Berlin
Institut f�r Medizinische Genetik und Humangenetik
Charit� - Universit�tsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson
________________________________________
Von: Nicole Washington [notifications@github.com]
Gesendet: Freitag, 6. M�rz 2015 18:50
An: monarch-initiative/human-disease-ontology
Betreff: [human-disease-ontology] fix grouping classes (#6)

i've been looking through our the ontology, i've found some issues.

many of the classes in the merged.obo are missing seemingly pedantic grouping classes.

for example,

id: OMIM:614480
name: Hypertriglyceridemia, Transient Infantile
is_a: DOID:630 ! genetic disease

id: OMIM:145750
name: familial hypertriglyceridemia
def: "A lipid metabolism disorder characterized by elevated triglyceride levels as a result of excess hepatic production of VLDL or heterozygous LPL deficiency." [url:http://en.wikipedia.org/wiki/Familial_hypertriglyceridemia]
comment: OMIM mapping confirmed by DO. [SN].
synonym: "Pure hyperglyceridemia" EXACT []
xref: DOID:0050527
is_a: DOID:3146 ! lipid metabolism disorder
is_a: DOID:630 ! genetic disease

are not related to one another except for both being genetic diseases. why isn't the former also a lipid metabolism disorder? or even better, why aren't they both classified as "hypertriglyceridemia"? that seems like a natural grouping class.

another

id: OMIM:606170
name: Genitopatellar Syndrome
is_a: DOID:630 ! genetic disease

in the text there is the description, "The SBBYS variant of Ohdo syndrome (603736) is an allelic disorder with overlapping features."

but it is also not classified:
[Term]
id: OMIM:603736
name: Ohdo Syndrome, Sbbys Variant
is_a: DOID:630 ! genetic disease

so i'd think they would be grouped together in some way.

when i just browse the ontology in protege, if you look under "genetic disease" there are many things that are siblings, but have nearly identical names, suggesting they should be subclasses of a more general disease, but are instead just a big fat flat list. some examples pulled only from A:

Acyl-coa Dehydrogenase * Deficiency Of
Adams-oliver Syndrome
Adrenal Hyperplasia, Congenital
Arthrogryposis * (only 3 of the 6 are classified as subtypes)
Atrial Fibrillation (only 4 of 8 are classified as subtypes)
Atrial Septal Defect (only 4 of 8 are classified as subtypes) ...
in fact, 2257 of the omim diseases in the merged file can't be classified into any upper-level grouping class at all except for a plain "genetic disease", which isn't too helpful.

migrated from monarch-initiative/disease-miner#8<https://github.com/monarch-initiative/disease-miner/issues/8>

�

**Comment by nicolevasilevsky** [comment]
old ticket, closing
