### ISSUE TITLE
MESH_D003410 Cri-du-Chat vs  MESH_C538482 Monosomy 5p

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#100]
This one is top ranking amongst the unlikelies. I suspect MESH has two classes where it should have one here (kboom treats merging classes within an ontology as an impossible state)

![img-mesh_c538482](https://cloud.githubusercontent.com/assets/50745/16351706/7e728d34-3a1c-11e6-888b-705803ebed9a.png)

**Comment by nicolevasilevsky** [comment]
@cmungall I am not sure what to do with this one. Monosomy 5p is a subclass of Cri-du-Chat syndrome in MeSH. Looks like Monosomy 5p is a supplementary concept in MESH and there is no text def:http://www.ncbi.nlm.nih.gov/mesh/?term=Monosomy+5p

It says it is mapped to Cri-du-Chat syndrome, does that mean MESH thinks they are equivalent?

**Comment by pnrobinson** [comment]
As far as I know cri du chat and monosomy 5p are synonymous.
See for instance
http://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=201&Disease_Disease_Search_diseaseGroup=Cri-du-chat-syndrome&Disease_Disease_Search_diseaseType=Pat&Disease(s)%20concerned=Monosomy-5p--Cri-du-chat-syndrome-&title=Monosomy-5p--Cri-du-chat-syndrome-&search=Disease_Search_Simple

Doesn’t this MeSH entry also imply they are synonymous?
https://www.nlm.nih.gov/cgi/mesh/2016/MB_cgi?mode=&index=3688&field=all&HM=&II=&PA=&form=&input=

**Comment by nicolevasilevsky** [comment]
@pnrobinson Yes, I think so. But it looks like monosomy 5p is asserted to be a subclass of Cri-du-Chat syndrome in the diagram above. Not sure how to address that.

**Comment by pnrobinson** [comment]
The subclass assertion seems to be simply a mistake. As far as I can see the MeSH data does not imply a subclass relation (http://www.nlm.nih.gov/cgi/mesh/2011/MB_cgi?exact&field=uid&term=C538482).
