### ISSUE TITLE
Check: Marfan syndrome

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#101]
MonDO hierarchy:

```
  is_a Orphanet:98028 ! Rare circulatory system disease
   is_a Orphanet:68362 ! Rare vascular disease
    is_a Orphanet:233655 ! Rare genetic vascular disease
     is_a Orphanet:285014 ! Rare disease with thoracic aortic aneurysm and aortic dissection
      is_a Orphanet:558 ! Marfan syndrome *** 
       is_a MESH:C535911 ! Marfan Syndrome type 2
       is_a MESH:C538192 ! Furlong syndrome
       is_a MESH:C563639 ! Cutis Laxa-Marfanoid Syndrome
       is_a OMIM:154700 ! Marfan syndrome *** 
       is_a OMIM:154750 ! Marfanoid Hypermobility Syndrome
       is_a OMIM:182212 ! Shprintzen-Goldberg Craniosynostosis Syndrome
       is_a OMIM:248760 ! Microcephaly - glomerulonephritis - marfanoid habitus
       is_a OMIM:248770 ! Marfanoid habitus - intellectual disability, autosomal recessive
       is_a OMIM:309520 ! Lujan-Fryns Syndrome
       is_a OMIM:609008 ! Marfanoid Habitus With Situs Inversus
       is_a OMIM:610168 ! Marfan syndrome type 2
```

Note the apparent duplicate marked `***`. 

This is the k-boom resolution of this subgraph:

![img-omim_616166](https://cloud.githubusercontent.com/assets/50745/16748580/c7d7ffd0-4779-11e6-93f8-cb620b4cd95b.png)

So @pnrobinson will undoubtedly correct me if I'm wrong here, and what we are seeing is that there is more than one type of Marfan. E.g.

http://www.ncbi.nlm.nih.gov/pubmed/18377530 "Marfan syndrome type II: there is more to Marfan syndrome than fibrillin 1."

We are consistent with orphanet here, as can be seen on the kboom resolution. However, we select the OMIM label to be the default. However, OMIM often names a specific disease like a generic disease, so we end up with a merged ontology that is logically fine but terminologically confusing.

It seems we should probably elect Orphanet to have priorities when it comes to labels.

**Comment by pnrobinson** [comment]
This is an area where nosologies break down. Many of the listed diseases (e.g., Marfan) are soo pleiotropic that they can be placed in many categories. Nonetheless, I think that MDs would expect to see these diseases as children of "Genetic aneurysm syndrome" (since the aortic manifestations represent the major clinical problem). I would not recommend futher subclassing (i.e., it is not really the case that Marfan syndrome type 2 is_a Marfan syndrome in a logical sense).

**Comment by cmungall** [comment]
I agree that the pleiotropy makes syndromic classification unwieldy. Note I only showed a single path as I wanted to focus on the Mf-Mf1-Mf2 triad. But with regards to the syndromic classication, if I were to show the full  graph you would see it under 'Rare disease with thoracic aortic aneurysm and aortic dissection', thanks to Orphanet (DO has a flatter classification).

But focusing on the Marfan, Marfan1 and Marfan2 quandary, can you elaborate on:

> i.e., it is not really the case that Marfan syndrome type 2 is_a Marfan syndrome in a logical sense

This is what Orphanet has:

 * Orphanet:558 ! Marfan syndrome _Marfan syndrome is a systemic disease of connective tissue characterized by a variable combination of cardiovascular, musculo-skeletal, ophthalmic and pulmonary manifestations_
     * Orphanet:284963 ! Marfan syndrome type 1
     * Orphanet:284973 ! Marfan syndrome type 2

Logically, this does not seem wrong. However, the parent definition is weak/underspecified. So perhaps when you say "it is not really the case that Marfan syndrome type 2 is_a Marfan syndrome in a logical sense" you have a stricter definition of (unqualified) "Marfan syndrome" in mind?

**Comment by cmungall** [comment]
Note DO has no definition for Marfan syndrome.

**Comment by cmungall** [comment]
Would calling the parent class Marfanoid syndrome help? E.g.

 * Marfanoid syndrome
    * Marfan syndrome type 1, aka Marfan syndrome, aka class Marfan syndrome
    * LDS, aka Marfan type 2

I understand better your point about syndromic classifications.

**Comment by cmungall** [comment]
Revisiting this

Orphanet has:

```
 / Orphanet:284993 ! Marfan and Marfan-related disorder *** 
  po Orphanet:115 ! Congenital contractural arachnodactyly
  po Orphanet:1885 ! Isolated ectopia lentis
  po Orphanet:2462 ! Shprintzen-Goldberg syndrome
  po Orphanet:284979 ! Neonatal Marfan syndrome
  po Orphanet:284984 ! Aneurysm-osteoarthritis syndrome
  po Orphanet:558 ! Marfan syndrome
   po Orphanet:284963 ! Marfan syndrome type 1
   po Orphanet:284973 ! Marfan syndrome type 2
  po Orphanet:60030 ! Loeys-Dietz syndrome
  po Orphanet:91387 ! Familial thoracic aortic aneurysm and aortic dissection
```

this causes issues since the OMIM 'canonical' Marfan is mapped to the parent

Here is the pre-merge graph (showing common UMLS IDs)

![image](https://cloud.githubusercontent.com/assets/50745/25031363/40c806ac-2081-11e7-98db-3f9f471caedc.png)

@pnrobinson do you think it makes sense to:

 * ignore Orphanet:558 ! Marfan syndrome
 * treat Orphanet:284963 ! Marfan syndrome type 1 as equiv to the OMIM
 * treat Orphanet:284973 ! Marfan syndrome type 2 as equiv to the LDS2, retaining the name of the latter
 * retain Orphanet:284993 ! Marfan and Marfan-related disorder as the broader grouping

**Comment by pnrobinson** [comment]
This is incorrect. AFAIK OMIM does not have Marfan syndrome type 2 because there are doubts as to whether this disease really exists. Please do not make them synonymous!

**Comment by jmcmurry** [comment]
I'm OK with whatever solution Peter deems best, provided we don't end up with diseases that have no phenotypes as this looks a bit odd.

**Comment by pnrobinson** [comment]
As mentioned there are doubts as to whether this diagnosis is medically valid and whether there should be an entry called Marfan type 2 at all. I personally have worked in this area for about ten years and have never seen a patient with what is called Marfan type 2, and so I would be for putting this diagnosis on our ignore list.

**Comment by jmcmurry** [comment]
Right, so let's just take the ID out of our corpus so that we don't end up with zombie entries. :)

**Comment by cmungall** [comment]
Remember our general strategy is to push fixes upstream, in this case to Orphanet - @annieolry what is Orphanet's position on this?

Thus far we have not obsoleted or excluded or merged any orphanet IDs in the merge process, but it sounds like we need to start doing this.

**Comment by cmungall** [comment]
And just to reiterate, the issue is that we have two Orphanet IDs, one for M, one for M-type-I. Our position is we believe these should be equivalent. I assume we want to take the parent as the primary
