### ISSUE TITLE
Change prefix for disease clusters ontology

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#103]
https://github.com/monarch-initiative/dipper/issues/355#issuecomment-235387072

`DC` is not registered on OBO. Also confusing since dc is often used as a prefix for Dublin Core.

Could also just place these in the MONDO ID space

**Comment by TomConlin** [comment]
When we have a prefix and uri decided on I will update the dipper curie map.
