### ISSUE TITLE
Inappropriate synonym in MPATH

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#105]
investigating

![img-ncit_c7580](https://cloud.githubusercontent.com/assets/50745/17561455/df3f76ee-5eda-11e6-85ae-92962e1e5882.png)

comes from:

```
[Term]
id: MPATH:230
name: sebaceous adenoma
namespace: mouse_pathology.ontology
def: "Adenoma of sebaceous cells; regular architecture of gland not mantained. Large numbers of immature germinative cells present. Mitoses. (M-8410/0)." [Pathbase:_Curation]
***synonym: "Epithelioma" RELATED [Pathbase:_Curation]
is_a: MPATH:219  ! adnexal and skin appendage tumor
is_a: MPATH:270  ! adenoma
```

this is arguably a BROAD syn, but this is a real stretch as it's broad enough to warrant a new concept

**Comment by nicolevasilevsky** [comment]
I think these should be separate terms. According to medscape, the following are subtypes of sebaceous neoplasms: sebaceous adenoma, sebaceous epithelioma (sebaceoma), sebaceous carcinoma, basal cell carcinoma with sebaceous differentiation, sebocrine adenoma, and sebomatricoma.

http://emedicine.medscape.com/article/1059260-overview
