### ISSUE TITLE
giant cell tumor of soft tissue and Undifferentiated Pleomorphic Sarcoma with Osteoclast-Like Giant Cells

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#106]
investigating

![img-mpath_410](https://cloud.githubusercontent.com/assets/50745/17561760/678e9a9c-5edc-11e6-8b26-64a77e4736fe.png)

due to syn match:

```
[Term]
id: MPATH:410
name: giant cell tumor of soft tissue
namespace: mouse_pathology.ontology
def: "Malignant or benign tumor of pluripotential mesenchymal stem cells giving rise to large multinucleated cells (M- 9251/1)." [Pathbase:_Pathology_Committee]
***synonym: "giant cell fibrous histiocytoma" RELATED [Pathbase:_Curation]
is_a: MPATH:404  ! soft tissue tumor

[Term]
id: NCIT:C8380
name: Giant Cell Fibrous Histiocytoma
def: "A sarcoma characterized by the presence of osteoclast-like giant cells and cellular pleomorphism." [NCIT:C8380]
***synonym: "Giant Cell Fibrous Histiocytoma" RELATED [NCIT:C8380]
synonym: "Malignant Giant Cell Neoplasm of Soft Parts" RELATED [NCIT:C8380]
synonym: "Malignant Giant Cell Tumor of Soft Parts" RELATED [NCIT:C8380]
synonym: "Malignant Osteoclastoma" RELATED [NCIT:C8380]
```

This is the two terms in NCIT:

![gct](https://cloud.githubusercontent.com/assets/50745/17561843/c1b596ce-5edc-11e6-8502-7f7f24bfc7b0.png)

**Comment by cmungall** [comment]
Defs:

  * NCIT:C8380 ! Giant Cell Fibrous Histiocytoma [DEF: "A sarcoma characterized by the presence of osteoclast-like giant cells and cellular pleomorphism."]
  * NCIT:C49107 ! Giant Cell Tumor of Soft Tissue [DEF: "A painless, well circumscribed tumor arising in soft tissue, usually of the upper and lower extremities. Morphologically, it is characterized by a multinodular growth pattern. The cellular infiltrate is composed of mononuclear round or oval cells and multinucleated osteoclast-like giant cells, in a rich vascular stroma.  It rarely metastasizes."]
 * MPATH:410 ! giant cell tumor of soft tissue  [DEF: "Malignant or benign tumor of pluripotential mesenchymal stem cells giving rise to large multinucleated cells (M- 9251/1)."]

**Comment by nicolevasilevsky** [comment]
According to this website, it seems like Giant Cell Fibrous Histiocytoma is synonymous with giant cell tumor of soft tissue.

http://www.pathologyoutlines.com/topic/softtissuemfhgiant.html

**Comment by cmungall** [comment]
Should we suggest a merge to NCIT?

**Comment by nicolevasilevsky** [comment]
Yes, I think so, from what I can tell, they seem equivalent.

**Comment by cmungall** [comment]
Again let's check definitions first
