### ISSUE TITLE
Review classification of leydig cell tumor

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#108]
## http://purl.obolibrary.org/obo/MPATH_328
- **Pr(G)**=0.41212121212121205 CONFIDENCE=0.3333333333333328 Success:true
- **SIZE**=3 (1 new axioms) 
  [img](target/img-MPATH_328.png)
- MEMBER: MPATH_328 leydig cell tumor
- MEMBER: NCIT_C4212 Benign Leydig Cell Tumor
- MEMBER: NCIT_C3188 Leydig Cell Tumor
- MPATH_328 leydig cell tumor EquivalentTo NCIT_C3188 Leydig Cell Tumor Pr= 0.85

**Comment by nicolevasilevsky** [comment]
![img-mpath_328](https://cloud.githubusercontent.com/assets/6722114/17563670/46b316e6-5ee5-11e6-8604-ab418ccf4bcb.png)

**Comment by cmungall** [comment]
What do we think of the MPATH class here?

```
[Term]
id: MPATH:328
name: leydig cell tumor
namespace: mouse_pathology.ontology
def: "Tumor derived from Leydig cells (M-8650/1)." [Mahler_M;_Sundberg_JP_(_1997)_Spontaneous_Leydig_cell_tumors_in_inbred_laboratory_mice_Lab_Animal_Science_47:148-52]
***synonym: "Interstitial cell tumor, benign" RELATED [Pathbase:_Curation]
synonym: "Leydig cell adenoma" RELATED [Pathbase:_Curation]
is_a: MPATH:323  ! gonadal somatic cell tumor
```

What do we make of the syn ***

**Comment by nicolevasilevsky** [comment]
I think this synonym should be removed, because a tumor could be malignant or benign. NCIt defines the Leydig cell tumor as a tumor where the malignancy status has not been established.

@cmungall Should I make a ticket for MPATH?

**Comment by cmungall** [comment]
Yes, we might also ask broadly what their synonym assigning methodology is, as we see a few like this

**Comment by nicolevasilevsky** [comment]
Sounds like we don't want to make tickets for MPATH after all? I'm not sure what the action item is here, except that MPATH_328 and NCIT_C4212 are not equiv.
