### ISSUE TITLE
Review classification of hydatidiform mole

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#112]
## http://purl.obolibrary.org/obo/MPATH_456
- **Pr(G)**=0.41212121212121205 CONFIDENCE=0.3333333333333328 Success:true
- **SIZE**=3 (1 new axioms) 
  [img](target/img-MPATH_456.png)
- MEMBER: MPATH_456 hydatidiform mole
- MEMBER: NCIT_C4699 Gestational Trophoblastic Tumor
- MEMBER: NCIT_C3110 Hydatidiform Mole
- MPATH_456 hydatidiform mole EquivalentTo NCIT_C3110 Hydatidiform Mole Pr= 0.85

**Comment by nicolevasilevsky** [comment]
![img-mpath_456](https://cloud.githubusercontent.com/assets/6722114/17564076/0e08db30-5ee7-11e6-9705-7beb0bf3247a.png)

**Comment by cmungall** [comment]
```
[Term]
id: MPATH:456
name: hydatidiform mole
namespace: mouse_pathology.ontology
def: "Vesicular or cystic tumor with hydropic villi resulting from the proliferation of trophoblast in the absence ( complete) or the presence ( partial) of an embryo. Most complete moles are homozygous androgenetic XX 46.(M-9100/0)." [Pathbase:_Curation]
synonym: "cystic mole" RELATED [Pathbase:_Curation]
***synonym: "gestational trophoblastic disease" RELATED [Pathbase:_Curation]
is_a: MPATH:454  ! trophoblastic tumor
```

**Comment by nicolevasilevsky** [comment]
NCIT_C4699 Gestational Trophoblastic Tumor
Definition: A diverse group of pregnancy-related tumors characterized by excessive proliferation of trophoblasts. Representative examples include hydatidiform mole, gestational choriocarcinoma, and placental site trophoblastic tumor.

MPATH_456 hydatidiform mole
Def: Vesicular or cystic tumor with hydropic villi resulting from the proliferation of trophoblast in the absence ( complete) or the presence ( partial) of an embryo. Most complete moles are homozygous androgenetic XX 46.(M-9100/0).

I think we should ignore the related syn and the NCIT_C4699 and MPATH_456 are not equiv.
