### ISSUE TITLE
Review classification of infiltrating duct carcinoma

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#115]
## http://purl.obolibrary.org/obo/NCIT_C4194
- **Pr(G)**=0.19607843137254904 CONFIDENCE=0.0 Success:true
- **SIZE**=3 (1 new axioms) 
  [img](target/img-NCIT_C4194.png)
- MEMBER: NCIT_C4194 Invasive Ductal Carcinoma, Not Otherwise Specified
- MEMBER: MPATH_282 infiltrating duct carcinoma
- MEMBER: NCIT_C4017 Ductal Breast Carcinoma
- MPATH_282 infiltrating duct carcinoma
  EquivalentTo NCIT_C4194 Invasive Ductal Carcinoma, Not Otherwise Specified Pr= 0.5

![img-ncit_c4194](https://cloud.githubusercontent.com/assets/6722114/17564449/31735446-5ee8-11e6-9301-e4c87d3ce597.png)

**Comment by nicolevasilevsky** [comment]
MPATH_282 infiltrating duct carcinoma
Derived from the mammary ductal epithelium and penetrating the stroma (M-8500/3).
has related syn: 
ductal carcinoma
Infiltrating ductal adenocarcinoma
duct adenocarcinoma

NCIT_C4017 Ductal Breast Carcinoma
Definition: A breast carcinoma arising from the ducts. While ductal carcinomas can arise at other sites, this term is universally used to refer to carcinomas of the breast. Ductal carcinomas account for about two thirds of all breast cancers. Two types of ductal carcinomas have been described: ductal carcinoma in situ (DCIS) and invasive ductal carcinoma. The latter often spreads to the axillary lymph nodes and other anatomic sites. The two forms of ductal carcinoma often coexist.
Synonyms:
Ductal Adenocarcinoma
Ductal Breast Carcinoma
Ductal Carcinoma
ductal carcinoma
Ductal Carcinoma of Breast
Ductal Carcinoma of the Breast
Duct Adenocarcinoma
Duct Carcinoma

I think the MPATH synonym is too broad (ductal carcinoma), and these are not equiv.

**Comment by cmungall** [comment]
is there a better class in NCIT?

**Comment by nicolevasilevsky** [comment]
I think the equivalences between NCIT_C4194 Invasive Ductal Carcinoma, Not Otherwise Specified and MPATH_282 infiltrating duct carcinoma are correct, but MPATH_282 infiltrating duct carcinoma is not equiv to NCIT_C4017 Ductal Breast Carcinoma.

**Comment by cmungall** [comment]
Do you think we should be using NOS terms? I understand why they are there, but using them directly (e.g in annotation) seems problematic. If we want to recommend use of NCIT globally then it should conform to OBO standards. Do we want to request a new NCIT term here?

**Comment by nicolevasilevsky** [comment]
Sure, I will request a new NCIT term.

**Comment by nicolevasilevsky** [comment]
@cmungall 
Actually, looking more closely at the NCIt term, they have these synonyms:
Invasive Ductal Carcinoma
Invasive Ductal Carcinoma of the Breast
Infiltrating Ductal Carcinoma of the Breast
Invasive Ductal Carcinoma of Breast
Infiltrating Ductal Carcinoma of Breast
Invasive Ductal Breast Carcinoma
Invasive Ductal Adenocarcinoma
Infiltrating Ductal Carcinoma
infiltrating ductal carcinoma
Infiltrating Ductal Carcinoma of the Breast
Infiltrating Ductal Breast Carcinoma
Infiltrating Ductal Adenocarcinoma

So do you think I should suggest a new term that is 'Invasive Ductal Carcinoma' with all of these synonyms as a new subclass of the term NCIT_C4194 Invasive Ductal Carcinoma, Not Otherwise Specified? 

Or would it be better suggest a revision to the label, to remove NOS?
