### ISSUE TITLE
MDO test case: hyperparathyroidism

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#12]
_From @cmungall on March 9, 2015 1:7_

Consider the _phenotype_ parathyroidism and its occurrence in various diseases:
http://www.monarchinitiative.org/phenotype/HP:0000843
(click 'disease' tab)

These are the types of DC:0000201 'hyperparathyroidism'
- [OMIM:145000](http://monarchinitiative.org/disease/OMIM_145000) ! HYPERPARATHYROIDISM 1
- [OMIM:145001](http://monarchinitiative.org/disease/OMIM_145001) ! HYPERPARATHYROIDISM 2
- [OMIM:239200](http://monarchinitiative.org/disease/OMIM_239200) ! Hyperparathyroidism, Neonatal Severe Primary
- [OMIM:600166](http://monarchinitiative.org/disease/OMIM_600166) ! Hyperparathyroidism, Primary, Caused By Water Clear Cell Hyperplasia
- OMIM:610071 HYPERPARATHYROIDISM 3

One might think we can use 'hallmark' to cluster diseases. However, the hallmark qualifier is lacking from phenotype association for the phenotype hyperparathyroidism for the above diseases.

For comparison, Orphanet classifications of OMIMs:
- [OMIM:145000](http://monarchinitiative.org/disease/OMIM_145000) ! HYPERPARATHYROIDISM 1      [Orphanet:99877](http://monarchinitiative.org/disease/Orphanet_99877) ! Familial parathyroid [adenoma,Orphanet:99879](http://monarchinitiative.org/disease/adenoma,Orphanet_99879) ! Familial isolated hyperparathyroidism
- [OMIM:145001](http://monarchinitiative.org/disease/OMIM_145001) ! HYPERPARATHYROIDISM 2      [Orphanet:99880](http://monarchinitiative.org/disease/Orphanet_99880) ! Hyperparathyroidism - jaw tumor syndrome
- [OMIM:239199](http://monarchinitiative.org/disease/OMIM_239199) ! Hyperparathyroidism, Neonatal Self-Limited Primary, with Hypercalciuria    **NOT-IN-ORDO**
- [OMIM:239200](http://monarchinitiative.org/disease/OMIM_239200) ! Hyperparathyroidism, Neonatal Severe Primary       [Orphanet:417](http://monarchinitiative.org/disease/Orphanet_417) ! Neonatal severe primary hyperparathyroidism
- [OMIM:256120](http://monarchinitiative.org/disease/OMIM_256120) ! Nephropathy, Deafness, and Hyperparathyroidism     [Orphanet:2668](http://monarchinitiative.org/disease/Orphanet_2668) ! Nephropathy - deafness - hyperparathyroidism
- [OMIM:600166](http://monarchinitiative.org/disease/OMIM_600166) ! Hyperparathyroidism, Primary, Caused By Water Clear Cell Hyperplasia       [Orphanet:99878](http://monarchinitiative.org/disease/Orphanet_99878) ! Primary parathyroids hyperplasia
- [OMIM:612089](http://monarchinitiative.org/disease/OMIM_612089) ! Hypophosphatemic Rickets And Hyperparathyroidism   **NOT-IN-ORDO**

To complicate matters, it seems we have no annotations for OMIM:610071 HYPERPARATHYROIDISM 3 (hence it doesn't show up above)

_Copied from original issue: monarch-initiative/human-disease-ontology#8_

**Comment by cmungall** [comment]
_From @pnrobinson on March 9, 2015 6:48_

Note that we have only used frequency annotations such as hallmark if there is data to this effect. Clearly, hyperparathyroidism is essential to many of these diseases. But this (and many other things) will require careful biocuration, and should be something that we achieve over the next 5 years. Note that as it stands "hallmark" is used only for the frequency, and thereby only indirectly to indicate whether a feature is essential for the disease definition. 
-peter


Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor in the Bioinformatics Division of the Department of Mathematics and Computer Science of the Freie Universit�t Berlin
Institut f�r Medizinische Genetik und Humangenetik
Charit� - Universit�tsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson
________________________________________
Von: Chris Mungall [notifications@github.com]
Gesendet: Montag, 9. M�rz 2015 02:07
An: monarch-initiative/human-disease-ontology
Betreff: [human-disease-ontology] MDO test case: hyperparathyroidism (#8)

Consider the phenotype parathyroidism and its occurrence in various diseases:
http://www.monarchinitiative.org/phenotype/HP:0000843
(click 'disease' tab)

These are the types of DC:0000201 'hyperparathyroidism'

 *   OMIM:145000<http://monarchinitiative.org/disease/OMIM_145000> ! HYPERPARATHYROIDISM 1
 *   OMIM:145001<http://monarchinitiative.org/disease/OMIM_145001> ! HYPERPARATHYROIDISM 2
 *   OMIM:239200<http://monarchinitiative.org/disease/OMIM_239200> ! Hyperparathyroidism, Neonatal Severe Primary
 *   OMIM:600166<http://monarchinitiative.org/disease/OMIM_600166> ! Hyperparathyroidism, Primary, Caused By Water Clear Cell Hyperplasia

One might think we can use 'hallmark' to cluster diseases. However, the hallmark qualifier is lacking from phenotype association for the phenotype hyperparathyroidism for the above diseases.

For comparison, Orphanet classifications of OMIMs:

 *   OMIM:145000<http://monarchinitiative.org/disease/OMIM_145000> ! HYPERPARATHYROIDISM 1 Orphanet:99877<http://monarchinitiative.org/disease/Orphanet_99877> ! Familial parathyroid adenoma,Orphanet:99879<http://monarchinitiative.org/disease/adenoma,Orphanet_99879> ! Familial isolated hyperparathyroidism
 *   OMIM:145001<http://monarchinitiative.org/disease/OMIM_145001> ! HYPERPARATHYROIDISM 2 Orphanet:99880<http://monarchinitiative.org/disease/Orphanet_99880> ! Hyperparathyroidism - jaw tumor syndrome
 *   OMIM:239199<http://monarchinitiative.org/disease/OMIM_239199> ! Hyperparathyroidism, Neonatal Self-Limited Primary, with Hypercalciuria
 *   OMIM:239200<http://monarchinitiative.org/disease/OMIM_239200> ! Hyperparathyroidism, Neonatal Severe Primary Orphanet:417<http://monarchinitiative.org/disease/Orphanet_417> ! Neonatal severe primary hyperparathyroidism
 *   OMIM:256120<http://monarchinitiative.org/disease/OMIM_256120> ! Nephropathy, Deafness, and Hyperparathyroidism Orphanet:2668<http://monarchinitiative.org/disease/Orphanet_2668> ! Nephropathy - deafness - hyperparathyroidism
 *   OMIM:600166<http://monarchinitiative.org/disease/OMIM_600166> ! Hyperparathyroidism, Primary, Caused By Water Clear Cell Hyperplasia Orphanet:99878<http://monarchinitiative.org/disease/Orphanet_99878> ! Primary parathyroids hyperplasia
 *   OMIM:612089<http://monarchinitiative.org/disease/OMIM_612089> ! Hypophosphatemic Rickets And Hyperparathyroidism

�

**Comment by cmungall** [comment]
_From @drseb on March 9, 2015 7:49_

Hi,

I just checked some of the examples:

> * OMIM:145000<http://monarchinitiative.org/disease/OMIM_145000> ! HYPERPARATHYROIDISM 1 Orphanet:99877<http://monarchinitiative.org/disease/Orphanet_99877> ! Familial parathyroid adenoma,Orphanet:99879<http://monarchinitiative.org/disease/adenoma,Orphanet_99879> ! Familial isolated hyperparathyroidism

Orphanet has no clinical signs for these 2.

> * OMIM:145001<http://monarchinitiative.org/disease/OMIM_145001> ! HYPERPARATHYROIDISM 2 Orphanet:99880<http://monarchinitiative.org/disease/Orphanet_99880> ! Hyperparathyroidism - jaw tumor syndrome

Orphanet has no clinical signs for this.

> * OMIM:239200<http://monarchinitiative.org/disease/OMIM_239200> ! Hyperparathyroidism, Neonatal Severe Primary Orphanet:417<http://monarchinitiative.org/disease/Orphanet_417> ! Neonatal severe primary hyperparathyroidism

This should be in your data, if you use our annotation data (not sure if). My pipeline produces the following line in phenotype_annotation.tab:
OMIM	239200	HYPERPARATHYROIDISM, NEONATAL SEVERE PRIMARY		HP:0000843	ORPHANET:417	TAS		hallmark		O	NEONATAL SEVERE PRIMARY HYPERPARATHYROIDISM|NSHPT|http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=417	2015.03.09	orphanet


Please note, that their disease mapping data is not always perfect. I ended up with the solution to only include Orphanet -> OMIM mapping, iff there is exactly one OMIM entry mapped. I can explain more if we manage to get a Skype-call for this and other topics soon.


Best,
Seb

**Comment by nicolevasilevsky** [comment]
old ticket, I think this can be closed
