### ISSUE TITLE
Review classification of hemangioma

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#122]
## http://purl.obolibrary.org/obo/MPATH_240
- **Pr(G)**=0.3736263736263736 CONFIDENCE=0.3333333333333328 Success:true
- **SIZE**=3 (1 new axioms) 
  [img](target/img-MPATH_240.png)
- MEMBER: MPATH_240 hemangioma
- MEMBER: NCIT_C3085 Hemangioma
- MEMBER: NCIT_C3084 Hemangioendothelioma
- MPATH_240 hemangioma EquivalentTo NCIT_C3085 Hemangioma Pr= 0.85

![img-mpath_240](https://cloud.githubusercontent.com/assets/6722114/17565555/c1cc145c-5eec-11e6-9f85-76dc7789d329.png)

**Comment by nicolevasilevsky** [comment]
MPATH_240 hemangioma
def:
Neoplasm derived from endothelial cells. May be of capillary or cavernous type with large vascular channels. (M-9130/0 + M-9120/0 respectively).
Syns:
Angioendothelioma.
Hemangioendothelioma, benign

NCIT_C3084 Hemangioendothelioma
Definition: A vascular proliferation characterized by the presence of prominent endothelial cells and the formation of vascular channels. Hemangioendotheliomas may display borderline or low grade characteristics.
synonyms:
Angioendothelioma
Hemangioendothelioma

I think the MPATH synonyms are too narrow.

**Comment by cmungall** [comment]
clearly kboom found the best configuration, and rejected the xref to Hemangioendothelioma, refusing even a subclass relationship interpretation. But this deserves further investigation.

"I think the MPATH synonyms are too narrow." - is it narrow? the concepts are siblings according to NCIT. 

![h](https://cloud.githubusercontent.com/assets/50745/18572347/fee35d50-7b7f-11e6-9679-37725e69d685.png)

However, there are subtleties here. AFAICT (IANACB) these are all blood vessel neoplasms, and the differentia is benignness (benign vs borderling). Does this also work for animals?

it's always worth comparing the text defs directly to see if true equivalence is justified. After all, MPATH was meant for mouse and NCIT mostly for humans.

```
id: NCIT:C3085
name: Hemangioma
def: "A benign vascular lesion characterized by the formation of capillary-sized or cavernous vascular channels." [NCIT:C3085]
```

```
MPATH_240 hemangioma
def:
Neoplasm derived from endothelial cells. May be of capillary or cavernous type with large vascular channels. (M-9130/0 + M-9120/0 respectively).
```

MPATH doesn't explicitly state benign. Can these be non-benign in non-human species? 

 * https://en.wikivet.net/Haemangioma
 * http://www.merckvetmanual.com/mvm/integumentary_system/tumors_of_the_skin_and_soft_tissues/connective_tissue_tumors.html
 * http://www.vcahospitals.com/main/pet-health-information/article/animal-health/vascular-tumors/704

Some of these to me suggest borderline, which would actually defend the MPATH synonym. I suspect this is not simple.

**Comment by nicolevasilevsky** [comment]
So, you are saying that the hemangioma definition in MPATH is more broad and may include benign and borderline cases? And maybe the MPATH term is not equiv to the NCIt Hemangioma term?

The HPO term uses the MPATH term in the logical definition, and the text def of the HPO term is:
A hemangioma is a benign tumor characterized by blood-filled spaces lined by benign endothelial cells. A hemangioma characterized by large endothelial spaces (caverns) is called a cavernous hemangioma (in contrast to a hemangioma with small endothelial spaces, which is called capillary hemangioma).

So it seems appropriate in this case to replace the NCIt term with the MPATH term.

**Comment by cmungall** [comment]
> So, you are saying that the hemangioma definition in MPATH is more broad and may include benign and borderline cases?

Yes. It may not be the intent, but as it's written it's broader

> And maybe the MPATH term is not equiv to the NCIt Hemangioma term?

it's not precisely equivalent according to the current text def. WHether this reflects species differences or simply different sources from the definition and a lack of precision in crafting the definitions, I don't know

> So it seems appropriate in this case to replace the NCIt term with the MPATH term.

You mean the other way round I think?

Yes, the HPO and the NCIt definitions are completely in accord. But we should also be thinking about linking with other species. Obviously this is not trivial...
