### ISSUE TITLE
Review classification of mesothelioma

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#131]
## http://purl.obolibrary.org/obo/NCIT_C3234
- **Pr(G)**=0.3736263736263736 CONFIDENCE=0.3333333333333328 Success:true
- **SIZE**=3 (1 new axioms) 
  [img](target/img-NCIT_C3234.png)
- MEMBER: NCIT_C3234 Mesothelioma
- MEMBER: MPATH_148 mesothelial hyperplasia
- MEMBER: MPATH_365 mesothelioma
- MPATH_365 mesothelioma EquivalentTo NCIT_C3234 Mesothelioma Pr= 0.85

![img-ncit_c3234](https://cloud.githubusercontent.com/assets/6722114/17565863/f7958e3c-5eed-11e6-9106-c7addc4977ea.png)

**Comment by cmungall** [comment]
Here we can see kboom did presumably the right thing and did not link these (the dashes represent a candidate).

This poses a question about the MPATH synonym:

```
[Term]
id: MPATH:148
name: mesothelial hyperplasia
namespace: mouse_pathology.ontology
def: "***Benign**** proliferation of mesothelial cells lining body cavities presenting as small solid cell clusters or multiple layers with columnar morphology and delicate eosinophilic cytoplasm." [Pathbase:_Mohr]
***synonym: "mesothelioma" RELATED [Pathbase:_Curation]
is_a: MPATH:602  ! hyperplastic tissue
```

MPATH says benign, but mesothelioma is usually non benign. I think the MPATH syn is trying to communicate a grouping based on tissue of origin. NCIT does this better:

```
   is_a NCIT:C3786 ! Mesothelial Neoplasm [DEF: "A benign or malignant neoplasm arising from mesothelial cells.  Mesothelial cells are the lining cells of the pleura and peritoneum. -- 2003"]
    is_a NCIT:C3234 ! Mesothelioma ***  [DEF: "A usually malignant and aggressive neoplasm of the mesothelium which is often associated with exposure to asbestos."]
```

**Comment by nicolevasilevsky** [comment]
I agree, I think the MPATH synonym is incorrect/too narrow.
