### ISSUE TITLE
Review classification of clear cell hidradenoma

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#134]
## http://purl.obolibrary.org/obo/NCIT_C7568
- **Pr(G)**=0.19781818181818178 CONFIDENCE=0.3333333333333328 Success:true
- **SIZE**=4 (1 new axioms) 
  [img](target/img-NCIT_C7568.png)
- MEMBER: NCIT_C7568 Nodular Hidradenoma
- MEMBER: NCIT_C7567 Clear Cell Hidradenoma
- MEMBER: MPATH_224 clear cell hidradenoma
- MEMBER: NCIT_C7563 Hidradenoma
- MPATH_224 clear cell hidradenoma EquivalentTo NCIT_C7567 Clear Cell Hidradenoma Pr= 0.85

![img-ncit_c7568](https://cloud.githubusercontent.com/assets/6722114/17565958/58232df4-5eee-11e6-9e2c-7cad7ff166c2.png)

**Comment by cmungall** [comment]
probably no action here, but what do we think of the marked MPATH syn:

```
[Term]
id: MPATH:224
name: clear cell hidradenoma
namespace: mouse_pathology.ontology
def: "Tumor derived from eccrine sweat glands composed of clear glycogen rich cells. ( M-84020 )." [Pathbase:_Curation]
synonym: "Eccrine acrospiroma" RELATED [Pathbase:_Curation]
****synonym: "nodular hidradenoma" RELATED [Pathbase:_Curation]
is_a: MPATH:219  ! adnexal and skin appendage tumor
is_a: MPATH:270  ! adenoma

[Term]
id: NCIT:C7568
name: Nodular Hidradenoma
namespace: mouse_pathology.ontology
def: "A benign epithelial neoplasm arising from the sweat glands. It presents as a nodular lesion usually in the scalp, trunk, and proximal extremities. It is characterized by a nodular growth pattern. Complete excision is curative." []
synonym: "Nodular Hidradenoma" EXACT []
synonym: "Solid and Cystic Hidradenoma" EXACT []
is_a: NCIT:C7563  ! Hidradenoma
```

**Comment by nicolevasilevsky** [comment]
Seems like nodular hidradenoma and clear cell nodular hidradenoma are distinct tumor subtypes, so I think the synonym should be removed from the MPATH term.

See http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3905631/
