### ISSUE TITLE
Review classification of adenoacanthoma

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#135]
## http://purl.obolibrary.org/obo/NCIT_C4106
- **Pr(G)**=0.2499999999999999 CONFIDENCE=0.33333333333333304 Success:true
- **SIZE**=3 (1 new axioms) 
  [img](target/img-NCIT_C4106.png)
- MEMBER: NCIT_C4106 Pseudoglandular Squamous Cell Carcinoma
- MEMBER: NCIT_C4200 Adenocarcinoma with Squamous Metaplasia
- MEMBER: MPATH_255 adenoacanthoma
- MPATH_255 adenoacanthoma EquivalentTo NCIT_C4200 Adenocarcinoma with Squamous Metaplasia Pr= 0.7

![img-ncit_c4106](https://cloud.githubusercontent.com/assets/6722114/17566019/904c5110-5eee-11e6-890a-a9a8724487ee.png)

**Comment by nicolevasilevsky** [comment]
These have overlapping synonyms:
MPATH has related syn: adenoid squamous cell carcinoma
NCIT_C4106 has full syn: adenoid squamous cell carcinoma

**Comment by cmungall** [comment]
do you believe the synonyms?

**Comment by nicolevasilevsky** [comment]
These synonyms are mentioned for each respective term in these sources:
http://medical-dictionary.thefreedictionary.com/adenoacanthoma (adenoid squamous cell carcinoma is a synonym for adenoacanthoma)

https://en.wikipedia.org/wiki/Squamous_cell_carcinoma (adenoid squamous cell carcinoma is a synonym for Pseudoglandular squamous cell carcinoma)

So it seems like perhaps the NCIt terms could be merged.

**Comment by cmungall** [comment]
did you check the definitions (textual and logical)?

**Comment by nicolevasilevsky** [comment]
Good point. The defs do differ. 

Adenocarcinoma with Squamous Metaplasia
def
A malignant neoplasm arising from glandular cells that includes focal or extensive areas of squamous metaplasia.

'Adenocarcinoma with Metaplasia'
 and (Disease_Has_Finding some 'Squamous Metaplasia of Malignant Cells Present')
-

Pseudoglandular Squamous Cell Carcinoma
def
A squamous cell carcinoma characterized by the formation of gland-like structures.

'Squamous Cell Carcinoma'
 and (Disease_Has_Finding some 'Pseudoglandular Pattern')

--
So I am not sure what the best thing to do is? It seems that some sources basically define these two as the same thing (based on the synonyms above from the medical dictionary and wikipedia.) And this article seems to suggest these terms are equivalent as well (http://www.amjorthopedics.com/home/article/pseudoglandular-squamous-cell-carcinoma/b1aa699ae2f6d5d4e8283143b2a39958.html?ooct=AJO-related).
