### ISSUE TITLE
append taxon to animal diseases in OMIA

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-disease-ontology-RETIRED#144]
Related to https://github.com/monarch-initiative/monarch-disease-ontology/issues/59 for human diseases, we should be able to append taxon to animal diseases. This will be needed for downstream enhancements to site search. https://github.com/monarch-initiative/monarch-app/issues/1317

<img width="462" alt="screen shot 2016-08-17 at 3 48 53 pm" src="https://cloud.githubusercontent.com/assets/3658863/17756038/53c88e3a-6492-11e6-91be-48d821deb09c.png">

**Comment by nicolevasilevsky** [comment]
This issue was moved to monarch-initiative/mondo#190
