### ISSUE TITLE
The problem of prototypes

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#149]
OMIM is a flat list (ignoring PS), with some diseases designated as 'prototypes'. There is no reliable way AFAICT to see if a disease is a prototype, but likely characteristics:
- ID ends in 00, first in phenotypic series if it exists
- It may be labeled "Foo type 1(A)" but this is far from guaranteed
- generic (DC-level) synonyms are associated with it
- generic disease description is attached to this entry

This can create some semantic confusion - can the prototype form be used in place of the generic form? I would say absolutely not, in the general case. However, we have to look on a case-by-case basis, e.g Marfan (#101).

The confusion is compounded when we merge with ORDO. Often ORDO will have a true generic form, and the generic form will be xreffed to all specific forms. ORDO will make these NTBT xrefs (good), apart from the prototype entry, which it assigns E. The problem is that we read this as 'likely to be equivalent', but this is a problem. Under OWL semantics, a generic form is not equivalent to a specific form, and there is no such thing as a prototype.

**Comment by sbello** [comment]
Hi Chris,
We (MGI and RGD) are working with DO to split out the specific OMIM terms out into individual DO terms. In cases where the prototype is subsumed in a specific record this will be treated as a specific record (ignore the 'prototype' aspect, see CMT1B 118200). In cases where the prototype (see Alzheimer, 104300) appears to be a 'generic disease' these will be left with the generic DO term. Ada from OMIM has stated that even the generic appearing terms in OMIM are not really 'generic'.
I haven't reviewed all the phenotypic series but from what I have looked at the#### in the PS#### is usually the prototype record ID.
Sue

**Comment by cmungall** [comment]
That's great, and of course DC already has very clear semantics, where the DC class is generic, and individual OMIMs always have SubClassOf relationship to the DC. Having all the DCs in DO will go a long way towards this. Of course, the problem with completely subsuming DCs into DO is that we lose these hard SubClassOfs and end up with weaker xrefs and not being able to reliably interpret these in the general case...

The current problem for us is primarily Orphanet, which asserts the Orphanet generic is an E match for the prototype OMIM

**Comment by sbello** [comment]
I'm also coming across cases in ORDO where an OMIM ID is an xref for both the main entity of the record and the 'included' entity. According to OMIM this should not be done (almost all of the time, although OMIM will at times break their own rule). OMIM generally creates included entities when they don't have enough information about a disease to warrant creating a separate record.
See for example the mapping of 606482, 607831 in ORDO

**Comment by sbello** [comment]
Sorry if I wasn't clear. I was thinking that the break up we're doing in DO of the OMIM terms may help you with the ORDO problem. Once this is done if an OMIM term and ORDO term are both mapped to a generic DO class, this would be a strong indication that the OMIM term is truly generic (or as Ada refers to them undefined). We are also mapping specific ORDO IDs to the new DO terms. You could potentially exclude OMIM IDs where the DO mapping is to a specific term but the ORDO is to a generic.

**Comment by pnrobinson** [comment]
Chiming in -- OMIM doesnt really seem like the provider of terms to describe general disease classes, since OMIM's scope is Mendelian disease. (I think this is what you mean by "Ada from OMIM has stated that even the generic appearing terms in OMIM are not really 'generic'."). ?

**Comment by sbello** [comment]
Correct, Ada is very definite that even things in OMIM that look like a generic class are not really generic they are 'undefined'. When more information becomes available OMIM will convert these entries into specific defined disease records. The problem in mapping these to disease ontologies is there is no good way to distinguish the OMIM undefined records from real generic terms. How do you distinguish the OMIM term 'Alzheimer disease' from the generic class 'Alzheimer disease'? In the DC, I didn't worry about this I just made all OMIM terms a child of the generic class.

**Comment by cmungall** [comment]
@pnrobinson I think we are all in agreement here. To try and restate. OMIM entries are not good candidates for disease groupings. Disease groupings are better handled by ontologies or ontology-like resources such as DC, DO, Orphanet, MESH (leaving aside for now any discussion of relative merits of each).

of course, we can still have groupings of mendelian diseases, it's just the grouping is not defined by any single gene

and I'm leaving aside the subtype layer in Orphanet, which in some cases are legitimate subtypes of OMIM IDs interpreted as classes.

With that understood, we are just noting a potential confusion in the way that to a naive observer who goes by the name or description, some OMIM entries look more generic than they actually are. This could be brushed aside as something everyone knows, but I'm not sure we know the extent to which this has caused confusion. It's certainly confusing if you look at how the different resources have treated Marfan (comment on this ticket: #101).

On top of that  we have the issue that I mentioned above and in the ticket that links here (Zellweger #148), where we have Orphanet making a cross-reference between a _generic_ Orphanet class and a _specific_ OMIM ID, __and it being categorized as "E"__. 


Here is the snippet of Orphanet (generic) Zellweger, and the mapping to OMIM:214100 `Peroxisome Biogenesis Disorder 1A (Zellweger)` (a specific form caused by a particular gene, the 'prototypical' form)

```
    <Disorder id="225">
      <OrphaNumber>912</OrphaNumber>
      <ExpertLink lang="en">http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&amp;Expert=912</ExpertLink>
      <Name lang="en">Zellweger syndrome</Name>
...
        <ExternalReference id="4070">
          <Source>OMIM</Source>
          <Reference>214100</Reference>
          <DisorderMappingRelation id="21527">
            <OrphaNumber>377807</OrphaNumber>
            <Name lang="en">E (exact mapping (the terms and the concepts are equivalent))</Name>
          </DisorderMappingRelation>
          <DisorderMappingICDRelation/>
          <DisorderMappingValidationStatus id="21611">
            <OrphaNumber>377819</OrphaNumber>
            <Name lang="en">Validated</Name>
          </DisorderMappingValidationStatus>
        </ExternalReference>
```

I'm not showing all the BTNT links to the other OMIM subtypes. Note this E mapping has a status of validated, so someone looked at this and decided they were "precisely equivalent" (this is what the orpha manual states). This could just be a simple mistake, but my hypothesis is that there is broad confusion regarding the distinction between prototypicality and genericity. 

As mentioned in other tickets (e.g. #139), the E/NTBT/BTNT relations are problematic and should be downweighted in the probabilistic algorithm. That should go some way to addressing the immediate problem and improving kboom performance. However, this feels unsatisfactory. If someone has gone to the trouble of looking at the Orphanet-OMIM xrefs and assigning them a category, I would like to be able to use this and assign a high weighting. Unfortunately, if this prototype-generic confusion is widespread it limits our ability to do this.

**Comment by cmungall** [comment]
@sbello 
> The problem in mapping these to disease ontologies is there is no good way to distinguish the OMIM undefined records from real generic terms. How do you distinguish the OMIM term 'Alzheimer disease' from the generic class 'Alzheimer disease'? In the DC, I didn't worry about this I just made all OMIM terms a child of the generic class

Precisely. I think your strategy makes sense.

However, we must also be cognizant of how these are used in annotation. If a MOD curator says gene G is a model of http://www.omim.org/entry/104300 `Alzheimer Disease; AD` what did they mean? Did they intend to say it models some portion of the phenotypic spectrum of general Alzheimers? Or that it's a model of the APP-mutant form? I think we should make it clear the OMIM ID refers purely to the latter, but I don't know that everyone got that memo.

**Comment by cmungall** [comment]
@sbello 
> Sorry if I wasn't clear. I was thinking that the break up we're doing in DO of the OMIM terms may help you with the ORDO problem

you were being perfectly clear, I wasn't reading correctly. So the plan is to add many DO classes corresponding to the different forms. So am I correct in that in accordance with this plan, there would be 20+ distinct DO classes for the different OMIMs for Alzheimers?

OK, I have heard of this plan a while ago but wasn't aware that it was an official design decision and that progress had been made. I'd also heard from Lynn that the policy was not to make subclasses if the different OMIM subtypes effectively presented as the same disease. Either way I'm not clear on the plan, it would be great to see more design documents for DO!

I can see the attraction in the plan. It will make the intended semantics much clearer, and you have the option of easily overriding labels (e.g. to avoid using a generic label for a specific class). You can also follow OBO ID policy and obsolete classes if the definitions change substantially. And you can have a clear OWL axiomatization in terms of genetic etiology.

But I have some concerns too. What informatics approaches will be applied to stay in sync with OMIM? Is the plan to do this incrementally or in batch? What timeline are we talking here?

**Comment by pnrobinson** [comment]
Hmm I really think that DO needs to get clearer about the structure of Mendelian vs. other diseases before doing this. It seems as if OMIM and ORDO are the authorities here, why not just import them as previously?

**Comment by cmungall** [comment]
When you say the structure, you mean the asserted hierarchy?

As to a combo of just OMIM and Orphanet, the answer is too long for this individual ticket. But even assuming we were to do this, the problem described in this ticket still stands. At least DO is relatively clear about what's a subclass and what's a superclass.

**Comment by cmungall** [comment]
The OMIM entry for polydactyly seems to be truly generic: http://www.omim.org/entry/603596
