### ISSUE TITLE
Nesting of syndromes "in other animals" under human equivalent

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-disease-ontology-RETIRED#152]
Having animal diseases nested under human disease equivalent doesn't strike me as correct, but it may well be overly complex to model it with a species agnostic parent node. Thoughts?

<img width="738" alt="screen shot 2016-09-02 at 2 24 27 pm" src="https://cloud.githubusercontent.com/assets/3658863/18218659/2cb6bd88-7119-11e6-875b-003270c28dfd.png">
<img width="368" alt="screen shot 2016-09-02 at 2 24 07 pm" src="https://cloud.githubusercontent.com/assets/3658863/18218660/2cb88b36-7119-11e6-8d10-e50709243c88.png">

**Comment by pnrobinson** [comment]
Would it be possible to have a node saying something like "aninmal models of X" and then show the corresponding model underneath? I agree it is odd to just mix them into a larger list.

**Comment by cmungall** [comment]
Agreed, Model-of X is better.

We'd want to tweak the hierarchy display to show this too (but this needs so many tweaks anyway!)

**Comment by cmungall** [comment]
Although 'model-of' isn't quite right for veterinary animals - their diseases may serve as models, but they may just have the disease. So a different relation like analogy or homology or shares-features-of may be better.

**Comment by jmcmurry** [comment]
> Although 'model-of' isn't quite right for veterinary animals

Precisely. Not sure how to fix it though. If you display human and animal equivalents as siblings, they are still children of a human-specific parent. Moreover, while the syndromic aspects may well be shared between humans and animals, the animal disease nosology may be quite different.

**Comment by cmungall** [comment]
I think the modeling issue is separate from the display issue. 

Also we wouldn't be starting out with much in the way of an animal nosology. The subclass hierarchy of OMIA is flat, the structure is in the links to human diseases
