### ISSUE TITLE
Retinoblastoma

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#154]
do:

```
          is_a DOID:768 ! retinoblastoma XREF: OMIM:180200
           is_a DOID:4647 ! trilateral retinoblastoma XREF: OMIM:180200
           is_a DOID:4648 ! familial retinoblastoma
           is_a DOID:4650 ! bilateral retinoblastoma
           is_a DOID:4651 ! unilateral retinoblastoma
           is_a DOID:4653 ! intraocular retinoblastoma
            is_a DOID:6938 ! pediatric intraocular retinoblastoma
           is_a DOID:4656 ! extraocular retinoblastoma
            is_a DOID:7747 ! pediatric extraocular retinoblastoma
```

kboom:

![img-ncit_c8495](https://cloud.githubusercontent.com/assets/50745/18653116/94bbdb72-7e8c-11e6-96ea-1a31d3b15cee.png)

A few things of note:
## Is the OMIM entry generic?

kboom has placed the generic-sounding [OMIM:180200 retinoblastoma](http://www.omim.org/entry/180200) as a superclass of DOID 'trilateral retinoblastoma'. It's priors weight against this as OMIMs are generally not grouping classes
- is the OMIM entry as generic as it sounds? It looks like it does encompass bilateral, trilateral, etc so the placement is justified
- what is the justification for DO xreffing only trilateral and not bilateral? kboom ends up getting it right but it would be better to have the source be clearer
## hereditary vs familial

should hereditary vs familial be swapped here? In fact is there much of a reason to distinguish these in the ontology?

Note DO doesn't have a term for the sporadic form (and it seems the sporadic form may sometimes have different genetic etiology, which would support an xref only from the OMIM to the hereditary/familiar form)?
## retinoblastoma vs retinal neuroblastoma

DOID has an xref between DOID:768 ! retinoblastoma and NCIT:C6956 ! retinal neuroblastoma. We can see why a naive text mining approach would think this, but I believe these are highly distinct (based on cell type of origin), and the DOID xref is wrong. Someone should check...

See also how these are distinct in NCIT:
- NCIT:C3270 ! Neuroblastoma [DEF: "A neuroblastic tumor characterized by the presence of neuroblastic cells, the absence of ganglion cells, and the absence of a prominent Schwannian stroma formation."]
- NCIT:C6956 ! Retinal Neuroblastoma [DEF: "A neuroblastoma arising from the retina."]
- NCIT:C7541 ! Retinoblastoma [DEF: "A malignant tumor that originates in the nuclear layer of the retina. As the most common primary tumor of the eye in children, retinoblastoma is still relatively uncommon, accounting for only 1% of all malignant tumors in pediatric patients. These tumors may be multifocal, bilateral, congenital, inherited, or acquired. Seventy-five percent of retinoblastomas are unilateral; 60% occur sporadically. A predisposition to retinoblastoma has been associated with 13q14 cytogenetic abnormalities. Patients with the inherited form also appear to be at increased risk for secondary nonocular malignancies such as osteosarcoma, malignant fibrous histiocytoma, and fibrosarcoma."]

![rn](https://cloud.githubusercontent.com/assets/50745/18653404/800bc370-7e8e-11e6-8cf1-d2785ae3fecc.png)

**Comment by nicolevasilevsky** [comment]
According to this definition, a Rb develops from any type of inner or outer retinal cell, which I think seems consistent with the NCIt definition. 

http://emedicine.medscape.com/article/1222849-overview?pa=C%2FXNYI3vX8OFng1JbdBNBQBmitu2CIztm0KtgeaxmWCR1ADiXPd8Yo2tIvIWpy1eCRVcTmEmU74bDWz7f0m8xEM903oaTexhZrGEfizZ20Q%3D

I agree that the DOID xref seems incorrect.

**Comment by nicolevasilevsky** [comment]
I agree that the classification of OMIM Retinoblastoma is a parent of Trilateral Retinoblastoma.

It seems like DO uses hereditary as a synonym for familial (see DOID:4648) and NCIt_C8495 uses familial as a synonym too. So should these be equivalent then?
