### ISSUE TITLE
Good sources for hierarchy of monogenic immune diseases

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/monarch-disease-ontology-RETIRED#155]
The classification seems to be state of the art and the second article has information about many new diseases. This should be useful for MONDO

Primary Immunodeficiency Diseases: an Update on the Classification from the International Union of Immunological Societies Expert Committee for Primary Immunodeficiency 2015immunology×
Picard C, Al-Herz W, Bousfiha A, Casanova JL, Chatila T, Conley ME, Cunningham-Rundles C, Etzioni A, Holland SM, Klein C, Nonoyama S, Ochs HD, Oksenhendler E, Puck JM, Sullivan KE, Tang ML, Franco JL, Gaspar HB
J Clin Immunol, 2015 – Review ⋯

Primary immunodeficiency diseases: Genomic approaches delineate heterogeneous Mendelian disordersimmunology×
Stray-Pedersen A, Sorte HS, Samarakoon P, Gambin T, Chinn IK ... (83 more) ... Gibbs RA, Shearer WT, Lyle R, Orange JS, Lupski JR
J Allergy Clin Immunol, 2016 – Journal Article ⋯

**Comment by cmungall** [comment]
There are a variety of ways to curate this

If the existing mondo classification is largely OK, and you just need to add and delete occasional assertions, you could just add entries to `curated-ptable.tsv` and add rows.

If you think it better to start from scratch then would be best done in Protege, using existing disease IDs, plus minting your own as-needed
