### ISSUE TITLE
familial hypercholesterolemia omim mapping concern

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#157]
_From @larrybabb on September 23, 2016 19:34_

https://monarchinitiative.org/disease/OMIM:144010
is a parent of
https://monarchinitiative.org/disease/OMIM:143890

in the emerge network we are trying to settle on an id that is the "group" term for familial hypercholesterolemia, so naturally I picked the parent above. However, geneticists using omim directly pick 143890 the child to represent this concept and then have the parent map to "Hypercholesterolemia, due to ligand-defective apo B".  I see that there is a DOID as an equivalent id on the parent omim above.

Why wouldn't the DOID concept be the parent of both?  I am a technical guy not a geneticist so please pardon my ignorance of the complexities behind how the hierarchy is assembled.

Thanks.

_Copied from original issue: monarch-initiative/monarch-app#1371_

**Comment by cmungall** [comment]
These are the 4 Hypercholesterolemia entries in OMIM:

 * OMIM:143890 ! HYPERCHOLESTEROLEMIA, FAMILIAL (various genes in OMIM, incl LDLR)
 * OMIM:144010 ! HYPERCHOLESTEROLEMIA, AUTOSOMAL DOMINANT, TYPE B (cause: APOB)
 * OMIM:603776 ! Hypercholesterolemia, Autosomal Dominant, 3 (cause: PCSK9)
 * OMIM:603813 ! Hypercholesterolemia, Autosomal Recessive (cause: LDLRAP1)

I believe it's fairly clear these belong to a grouping of inherited/familial Hypercholesterolemias.

What is confusing is that OMIM:143890 is named generically. This makes it look like a case of issue #149

In fact OMIM:143890 should be a sibling of the others (and IMO a name that would not be confused with a name for a grouping class that should be chosen).

kboom should be resilient in the face of these naming issues. However, there seem to be some pervasive issues and confusion in some of the sources going in, resulting in things becoming conflated. I'm looking in more detail and will report back later.

**Comment by pnrobinson** [comment]
http://www.omim.org/entry/143890 seems to be conflating a Mendelian form with LDLR and more polygenic forms that may in many cases include variants on the other listed genes. So this entry probably should be split into two entities.

**Comment by cmungall** [comment]
My comments from the previous ticket: 

The short answer is that we were assigning high weight to assignments orphanet makes about whether an OMIM and Orphanet pairing is likely to be exact vs narrower-to-broader. It turns out this was a bad idea, because often Orphanet treats the first entry in the phenotypic series as being the broader concept.

If we take your example Orphanet:90647 'Jervell and Lange-Nielsen syndrome', we can see that Orphanet says this is an EXACT match to OMIM:220400 ! Jervell and Lange-Nielsen Syndrome 1, but a BTNT match (broad-to-narrow) match to OMIM:612347 ! Jervell and Lange-Nielsen Syndrome 2

In fact, the Orphanet class is really broader than *both*. The general issue is covered here: https://github.com/monarch-initiative/monarch-disease-ontology/issues/149

You can see why Orphanet does this in many cases - often the first entry in a phenotypic series is written *as if* it were the broader concept. But it's not correct.

As a result of this, we're downweighting the Orphanet E-vs-BTNT assignments, as there are other issues with these.

There's a bit more to it, but the TL;DR is that this is much improved in the next release.
