### ISSUE TITLE
Lipomatosis vs lipoma

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#159]
"Lipomatosis is believed to be an autosomal dominant condition in which multiple lipomas are present on the body" (https://en.wikipedia.org/wiki/Lipomatosis)

This seems like a fairly clear distinction between a disease and a phenotype/tumor/entity. However, as we know from cases like #138 when we have both X and susceptibility-to-X confusion arises.

kboom is having issues resolving this satisfactorily. Here is a subset of the pre-merged graph:

![img-doid_3153](https://cloud.githubusercontent.com/assets/50745/18811763/e3676ace-8270-11e6-9fab-394142dd56f1.png)

NCIT treats these as sibs, under Benign Lipomatous Neoplasm

```
     is_a NCIT:C4502 ! Benign Lipomatous Neoplasm ***  [DEF: "A benign mesenchymal neoplasm composed of adipose (fatty) tissue.  The most common representative of this category is the lipoma."]
      is_a NCIT:C27483 ! Lipoblastoma [DEF: "A lipoma usually occurring in the extremities of young children (usually boys). It is characterized by lobules of adipose tissue, separated by fibrous septa.  The adipose tissue is composed of mature adipocytes and lipoblasts. The lipoblasts may be scarce, depending on the age of the patient."]
      is_a NCIT:C3192 ! Lipoma [DEF: "A benign, usually painless, well-circumscribed lipomatous tumor composed of adipose tissue."]
      is_a NCIT:C3193 ! Lipomatosis [DEF: "A neoplastic process characterized by diffuse overgrowth of mature adipose tissue."]
      is_a NCIT:C4255 ! Lipoblastomatosis [DEF: "A benign disorder characterized by the presence of multiple lipoblastomas."]
```

However, when MEDIC wants to classify OMIM:151900 ! Lipomatosis, Multiple it places it under both lipoma and lipomatosis in MESH

DO has:

![d](https://cloud.githubusercontent.com/assets/50745/18811785/a203a8ee-8271-11e6-90bb-bd7e21275716.png)

note the highlighted axioms:

```
id: DOID:3315
name: lipoma
namespace: disease_ontology
alt_id: DOID:3154
alt_id: DOID:9291
def: "A cell type benign neoplasm that is composed of lipocytes." [url:http://en.wikipedia.org/wiki/Benign_tumor]
comment: OMIM mapping confirmed by DO. [SN].
synonym: "LIPOMATOSIS, FAMILIAL MULTIPLE" EXACT []
synonym: "Lipomatous neoplasm (morphologic abnormality)" EXACT [SNOMEDCT_2005_07_31:115227001]
synonym: "Lipomatous tumor" EXACT [NCI2004_11_17:C4248]
synonym: "benign lipomatous tumor" EXACT []
synonym: "benign tumor of Adipose tissue" EXACT [NCI2004_11_17:C4502]
***synonym: "multiple lipomatosis" EXACT []
synonym: "tumor of adipose tissue (disorder)" EXACT [SNOMEDCT_2005_07_31:254831005]
xref: ICD10:D17
xref: ICD10:D17.9
xref: ICD9:214
xref: ICD9:214.9
xref: MESH:D008067
xref: MESH:D018205
xref: NCIT:C3192
xref: NCIT:C4248
xref: NCIT:C4502
***xref: OMIM:151900 ! Lipomatosis, Multiple
xref: SCTID:115227001
xref: SCTID:154612003
xref: SCTID:189018005
xref: SCTID:189776008
xref: SCTID:189785008
xref: SCTID:254827004
xref: SCTID:254830006
xref: SCTID:254831005
xref: SCTID:46720004
xref: SCTID:93163002
xref: UMLS:C0023798
xref: UMLS:C0206631
xref: UMLS:C0346118
is_a: DOID:0060084  ! cell type benign neoplasm      
```

The marked terms should _probably_ be moved over to lipomatosis here.

All round there are a few thing that could be fixed, but the underlying problem is the lack of a design pattern for susceptibility-to-X vs X. Without this, the decision on how to make a hierarchy is largely arbitrary, and different sources will do this differently, leading to merge issues.

**Comment by pnrobinson** [comment]
I do not think lipomatosis is necessarily dominant or even necessarily Mendelian. The wikipedia article is too narrow.

**Comment by cmungall** [comment]
It looks like wikipedia is also confused about the distinction between a lipoma, (generic) lipomatosis, and  familial multiple lipomatosis. See my comments here: https://en.wikipedia.org/wiki/Talk:Lipoma#Lipomatosis_vs._Lipoma

But the main point here is not the various forms of lipomatosis, but rather the lipoma-lipomatosis confusion
