### ISSUE TITLE
superclass to hold 8+ skin-hair-eye pigmentation diseases?

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-disease-ontology-RETIRED#160]
Given how many of these there are, I'm wondering if there should be a superclass to hold them?
- Skin-Hair-Eye Pigmentation, Variation In, 10
- Skin-Hair-Eye Pigmentation, Variation In, 11
- Skin-Hair-Eye Pigmentation, Variation In, 4
- Skin-Hair-Eye Pigmentation, Variation In, 5
- Skin-Hair-Eye Pigmentation, Variation In, 6
- Skin-Hair-Eye Pigmentation, Variation In, 7
- Skin-Hair-Eye Pigmentation, Variation In, 8
- Skin-Hair-Eye Pigmentation, Variation In, 9

Also, it looks like our list is missing types 1,2,3? These may have been subsumed into the others, but thought I'd mention exploring it.

**Comment by cmungall** [comment]
We should be excluding these, because they're not diseases.

In fact we do exclude the OMIM entries.

However, they sneak in via MESH. Including MESH is a real pain.

I think that anything we exclude from OMIM that is also in MESH should go into the exclusion list. Will add.

**Comment by nicolevasilevsky** [comment]
Looks like these are no longer in MONDO, closing
