### ISSUE TITLE
Charcot Marie Tooth dual parentage

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-disease-ontology-RETIRED#161]
Motor Peripheral Neuropathy
Sensory Peripheral Neuropathy

Generation of intermediate nodes semi-automatically? eg. Motor and sensory...

@pnrobinson @mellybelly @nicolevasilevsky

**Comment by pnrobinson** [comment]
As suggested on the call by MH, it would be great to create a suggested list and vet it by hand. 
I would make time for this in November of early December and would suggest we go through 2-3 major categories a week -- I think it would be good if we try to stick to community norms and integrate them wherever possible, so we will need to do a little research.

**Comment by nicolevasilevsky** [comment]
This issue was moved to monarch-initiative/mondo#189
