### ISSUE TITLE
Add MEDDRA to MONDO

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-disease-ontology-RETIRED#166]
Note that MEDDRA does not have an open license. Might be able to get away with this: http://www.meddra.org/subscription/special-licences

ORDO, UMLS, others already contains MEDDRA xrefs.

**Comment by drseb** [comment]
HPO also references MedDRA

**Comment by mellybelly** [comment]
@drseb how often are these updated? probably could have some regular pipeline that maps to both HPO and Mondo?

**Comment by drseb** [comment]
We semi-manually curated these once and didn't touch them since then.

**Comment by drseb** [comment]
I think usually one writes "semi-automatically". Sry

**Comment by nicolevasilevsky** [comment]
I think this has been addressed, closing
