### ISSUE TITLE
Add equivalence class IDs and labels to ClinGen file

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-disease-ontology-RETIRED#17]
I think it would be easier for folks to review the outcomes of the report if they can see everything in EXCEL

You could take each string provided, and then in a different column show each ID and each primary label associated with it. then you can also show all the equiv classes and their IDs and labels. In a different column, add the superclass ID and label. 

We might try creatively sorting or color coding the same matches for each gene or some such in the excel for easy review.

**Comment by nicolevasilevsky** [comment]
@mellybelly can I close this ticket?
