### ISSUE TITLE
islet cell tumor

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#198]
![img-mesh_d007340](https://cloud.githubusercontent.com/assets/50745/23928771/fe02b98e-08de-11e7-83c3-8697c2acafd6.png)

a resolution could not be found, likely due to malignancy disjointness violation

red links indicate equivalence axioms selected by greedy method, high confidence.

dotted lines are xrefs annotated with weights (SUB-SUP-EQUIV) for which a configuration could not be found

**Comment by nicolevasilevsky** [comment]
I made some comments on this ticket. (I realize this is an old ticket but since it was still open, I figured I could comment on it.) @cmungall let me know if I should update a file.

![image](https://cloud.githubusercontent.com/assets/6722114/24734007/02e1611e-1a30-11e7-98b9-ea5afd740714.png)

**Comment by cmungall** [comment]
can you explain the reason for a subclass for MESH islet cell tumor syndrome? Perhaps this would be better as susceptible-to? 

Can you make your edits for this in a branch and make a pull request?
