### ISSUE TITLE
13. Parkinsonism due to ATP13A2 deficiency -> Kufor-Rakeb syndrome

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#201]
The Orphanet disease 'Parkinsonism due to ATP13A2 deficiency' and 'Kufor-Rakeb syndrome' are both mapped to the same [OMIM term](http://omim.org/entry/606693) (KUFOR-RAKEB SYNDROME; KRS). Both diseases are due to mutations in the same gene too, so I think this subclass assertion may be correct. Should I discuss with Annie? (It doesn't seem like I tag her in here, maybe we need to add her to this repo?)

See [report](https://github.com/monarch-initiative/monarch-disease-ontology/blob/master/src/reports/new-subclass/orphanet.md#parkinsonism-due-to-atp13a2-deficiency---kufor-rakeb-syndrome)
![image](https://cloud.githubusercontent.com/assets/6722114/24158112/9c92eca2-0e18-11e7-99d1-0048e62c8be8.png)

**Comment by cmungall** [comment]
Yes, add Annie

Note in this case the resolution agrees with Orphanet E/NTBT/BTNT calls. 
Still seems odd.

**Comment by nicolevasilevsky** [comment]
emailed annie on 04/05/17

**Comment by nicolevasilevsky** [comment]
Adding @annieolry
