### ISSUE TITLE
21. Classic multiminicore myopathy ->  Central core disease

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#209]
21. Classic multiminicore myopathy ->  Central core disease

In this image, classic multiminicore myopathy is not a direct subclass of central core disease, but is a subclass of multiminicore myopathy, which is a subclass of central core disease, which is another issue #210 

I don't think there is an issue here, correct me if I am missing something.

![image](https://cloud.githubusercontent.com/assets/6722114/24735231/c475ade8-1a36-11e7-916c-9bf0b941a843.png)
Updated picture

**Comment by cmungall** [comment]
See also #211

**Comment by cmungall** [comment]
1. Should the mesh be part of the larger clique?
 2. Do we believe the OMIM class is generic enough to have 2 levels beneath it?

Remember, OMIM labels are often deceptively generic sounding, when they actually refer to a specific form. The Orphanet NTBT is based on a generic reading I bet, but as the above shows, a generic reading doesn't make sense!

We really need to read the literature here, we can't make assumptions based on names. See for example:

 - https://ghr.nlm.nih.gov/condition/multiminicore-disease
 - http://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=597

From a very cursory read, it seems the correct representation is

 - minicore aka central core disease (grouping)
    - classic form (SELENON gene)
    - atypical form (RYR1) <-- OMIM ID here


Also can you link to the full image in these tickets? It can help to see the bigger picture [eg this one](https://github.com/monarch-initiative/monarch-disease-ontology/raw/master/src/reports/new-subclass/target/img-Orphanet_324604.png)

**Comment by nicolevasilevsky** [comment]
In response to whether MeSH should be part of the larger clique - I think so, DO cross ref's the MeSH term.

**Comment by nicolevasilevsky** [comment]
I agree with your classifications of the central core disease
"minicore aka central core disease (grouping)
classic form (SELENON gene)
atypical form (RYR1) <-- OMIM ID here"

**Comment by nicolevasilevsky** [comment]
I think the classification of multiminicore disease as a subclass of central core disease is okay

**Comment by nicolevasilevsky** [comment]
Not sure if Orphanet_178145 Moderate multiminicore disease with hand involvement should be a subclass of Orphanet_597 though, I think that sublcass assertion is made because OMIM includes that disease in their description of Central Core Disease of Muscle.
