### ISSUE TITLE
Encoding of non-ASCII characters

### ISSUE THREAD

**Issue by mwilliamson-healx** [monarch-initiative/monarch-disease-ontology-RETIRED#215]
Non-ASCII characters seem to be incorrectly encoded, at least some of the time. For instance:

* [persistent Mullerian duct syndrome](https://monarchinitiative.org/disease/OMIM%3A261550) has "Persistent MC<llerian derivatives" as a synonym (it should be Müllerian)

* [Waldenström macroglobulinemia](https://monarchinitiative.org/disease/Orphanet:33226) has the name "WaldenstrC6m macroglobulinemia"

**Comment by nicolevasilevsky** [comment]
this has been fixed
