### ISSUE TITLE
35	Hb Bart's hydrops fetalis -> Non-immune hydrops fetalis

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#224]
I think this subclass assertion is legitimate. They both cross ref the same [OMIM record](https://omim.org/entry/236750) and Hb Bart's hydrops fetalis seems to have all the characteristics of NIHF.

![image](https://cloud.githubusercontent.com/assets/6722114/24223906/93f38a4a-0f15-11e7-8af0-fe527cece8b7.png)

**Comment by cmungall** [comment]
I think you're right based on your comments in #223 - will you tag orphanet?

As an aside, DO used to have HF:

```
[Term]
id: DOID:1097
name: hydrops fetalis
namespace: disease_ontology
def: "Hydrops fetalis is a alpha thalassemia characterized by an abnormal accumulation of serous fluid in the fetal tissues, as in erythroblastosis fetalis." [stedman:rlc, url:http://www2.merriam-webster.com/cgi-bin/mwmednlm?book=Medical&va=Hydrops%20fetalis]
is_obsolete: true
```

no obsoletion reason provided, but perhaps because it's a phenotype. From HPO:

![image](https://cloud.githubusercontent.com/assets/50745/24224550/f7d6a5f8-0f18-11e7-9cf8-82597a875ca0.png)


cc @pnrobinson

**Comment by nicolevasilevsky** [comment]
emailed Annie because I can't tag her here for some reason

**Comment by annieolry** [comment]
I think Hb Bart's hydrops fetalis is one cause of nonimmune hydrops fetalis. We need to assess internally how to represent that. We probably need to complete with other causes. I will let you know. 
Thanks

**Comment by pnrobinson** [comment]
hydrops fetalis is conceptualized here as a phenotypic feature, a kind of severe edema at birth. The HPO should definitely not start to put all of the etiologies of hydrops in. Hb Barts is an observable phenotype that can be a cause of hydrops but we are not coding pathophysiology.

**Comment by nicolevasilevsky** [comment]
@annieolry
