### ISSUE TITLE
36	Rare renal tumor -> Genetic renal tumor

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#225]
There aren't any details on the Orphanet pages but I think this looks okay.

![image](https://cloud.githubusercontent.com/assets/6722114/24224065/680a9986-0f16-11e7-9102-93d5513d7f68.png)

**Comment by cmungall** [comment]
well I guess it depends how you define genetic tumor. Obviously all are genetic in some sense, but there could rare non-germline tumors?

I'm not sure it's worth pointing this out, there are deep issues with the upper level rare/genetic/rare-genetic X classifications in Orphanet. We try and collapse as many of these as a preprocessing step in mondo.

**Comment by nicolevasilevsky** [comment]
should we close this then?

**Comment by pnrobinson** [comment]
We should go back to Orhpanet on this one. Genetic renal tumor is not a good term name. I suppose this is refering to items such as https://www.omim.org/entry/605074?search=renal%20carcinoma&highlight=carcinomatous%20carcinoma%20renal. If this is the case, then it is not synonymous with the DO term. The name of the term should be Mendelian renal tumor predisposition syndrome, or something along those lines.

**Comment by nicolevasilevsky** [comment]
emailed Annie, I still can't tag her

**Comment by nicolevasilevsky** [comment]
@annieolry
