### ISSUE TITLE
37	Adult T-cell leukemia/lymphoma -> Precursor T-cell acute lymphoblastic leukemia

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#226]
These are siblings in DO, and from what I can tell, it seems that is the correct classification.

![image](https://cloud.githubusercontent.com/assets/6722114/24224214/2c6c9b26-0f17-11e7-8f97-3b77a588e965.png)

**Comment by cmungall** [comment]
If NCIT does not have this then I am skeptical.

**Comment by nicolevasilevsky** [comment]
@cmungall I'm not sure I understand what you mean, these terms are in NCIT.

I think my statement above is wrong though, the two terms are siblings in DO. Based on looking at the other terms too, I don't think this subclass assertion is correct.
