### ISSUE TITLE
42 Sialidosis type 2 -> Mucolipidosis

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#241]
A synonym of MeSH_C537366 Neuramindase I deficiency is Sialidosis type 2
A synonym for MeSH_D009081 Mucolipidoses is Sialidosis

Orphanet has Mucolipisoses and Sialidosis as separate terms, whereas MeSH merges them.
 
![image](https://cloud.githubusercontent.com/assets/6722114/25348668/d4e215a8-28d3-11e7-81b5-806ea4e23fc5.png)

See [report](https://github.com/monarch-initiative/monarch-disease-ontology/blob/master/src/reports/new-subclass/orphanet.md#mucolipidosis-type-iv---mucolipidosis)

**Comment by pnrobinson** [comment]
See here
https://rarediseases.org/rare-diseases/sialidosis/
https://omim.org/entry/256550
Sialidosis is mucolipidosis type I

**Comment by cmungall** [comment]
In that case, there seems to be a few things needing corrected in Orphanet:

Orphanet has the following xrefs:

 * Orphanet:812 (S. type I) ntbt OMIM:256550
 * Orphanet:87876 (S. type II) e OMIM:256550

In fact, these should both be removed and replaced by

 * Orphanet:309294 (generic S) e OMIM:256550

Then, presumably Orphanet needs to add a subclass relationship:

 * Orphanet:309294 (generic S) SubClassOf Orphanet:79212 (mucolipidosis)

@nicolevasilevsky can you follow up?

**Comment by nicolevasilevsky** [comment]
@annieolry can you address these changes in Orphanet that Chris' mentions above?

**Comment by nicolevasilevsky** [comment]
added ticket to Orphanet tracker, closing here
