### ISSUE TITLE
Hemihypertrophy subClassOf Macroglossia?

### ISSUE THREAD

**Issue by siiraa** [monarch-initiative/monarch-disease-ontology-RETIRED#242]
Orphanet_373 Hemihypertrophy by definition is an overgrowth characterized by an aymmetric regional body overgrowth, invoving at least one limb.

Macroglossia Orphanet_156207 (http://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_156207) is the presence of an excessively large tongue, appearing to be the parent of Hemihypertrophy.

Does this sound right? Something feels a bit off to me.

Thank you,
Sira

**Comment by nicolevasilevsky** [comment]
This issue was moved to monarch-initiative/mondo#186
