### ISSUE TITLE
Consolidating documentation of MONDO-Orphanet classification

### ISSUE THREAD

**Issue by siiraa** [monarch-initiative/monarch-disease-ontology-RETIRED#244]
There are a few standing questions and the activities of reclassifying hanging ORDO terms that need to be documented. There has been an on-going conversation on the combined effort of this re-classification. https://docs.google.com/document/d/1ePEudnqb4w0yxM0whi5TPJWf54SyaRznj2Qy_mi4f9A/edit?usp=sharing is where all the documentation from all involved parties should go @cmungall @mellybelly @drseb

**Comment by nicolevasilevsky** [comment]
This issue was moved to monarch-initiative/mondo#184
