### ISSUE TITLE
Consider making xrefs mirror equivalence axioms

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/monarch-disease-ontology-RETIRED#246]
OMIM:182900 is an xref for both 
id: OMIM:182900
name: hereditary spherocytosis type 1
and
id: DOID:12971
name: hereditary spherocytosis
I think that only the former instance is correct.

**Comment by cmungall** [comment]
We should better document this

xref doesn't mean equivalent. The OWL and JSON files have equivalencies. We could do a better job of marking things out in the obo. We could simply remove all xrefs in advance and make xref mirror the equivalency axioms

**Comment by nicolevasilevsky** [comment]
This issue was moved to monarch-initiative/mondo#182
