### ISSUE TITLE
Is there a plan to version MONDO?

### ISSUE THREAD

**Issue by larrybabb** [monarch-initiative/monarch-disease-ontology-RETIRED#252]
As users of MONDO, we would like to have some level of control over the releases we download. Users want to be able to speak to release differences and track when new versions of MONDO are available for updating.

Is there a plan to provide this? If so, when? If not, why?

Thanks.

**Comment by nicolevasilevsky** [comment]
This issue was moved to monarch-initiative/mondo#178
