### ISSUE TITLE
Review Choroid Plexus Carcinoma mapping

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#260]
NCIT_C4715 | Choroid Plexus Carcinoma | SubClassOf | OMIM_260500 | Papilloma of Choroid Plexus
-- | -- | -- | -- | --

![image](https://user-images.githubusercontent.com/6722114/29056387-935e2cde-7bb7-11e7-9142-d0be234b097b.png)

**Comment by cmungall** [comment]
I think the xrefs connecting the papilloma to the carcinoma are wrong. The carcinoma can arise from the papilloma, but this is a different kind of relationship.

**Comment by nicolevasilevsky** [comment]
Where do you see the xref? I don't see any xrefs in NCIt or OMIM to each other.

I agree this seems incorrect.

What is the action for this?
