### ISSUE TITLE
NCIT_C4504	Malignant Breast Phyllodes Tumor

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#281]
NCIT_C4504 | Malignant Breast Phyllodes Tumor | SubClassOf | DOID_3016 | breast malignant phyllodes tumor
-- | -- | -- | -- | --

![image](https://user-images.githubusercontent.com/6722114/29057990-ccefa90e-7bc2-11e7-9f23-6671e0548afe.png)

**Comment by nicolevasilevsky** [comment]
DO has a syn that xrefs NCIT_C4504, and it also xrefs C7575. I think they should remove the xref to C7575, and DO_3016 is equiv to C4505

![image](https://user-images.githubusercontent.com/6722114/29092314-cafc472e-7c3a-11e7-8219-d4c0cb0d16d7.png)

![image](https://user-images.githubusercontent.com/6722114/29092361-f1bd7c34-7c3a-11e7-98c4-b4417634dad0.png)

**Comment by cmungall** [comment]
#262
