### ISSUE TITLE
NCIT_C7430 Malignant Exocrine Pancreas Neoplasm

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#283]
NCIT_C7430 | Malignant Exocrine Pancreas Neoplasm | SubClassOf | DOID_1795 | tumor of exocrine pancreas
-- | -- | -- | -- | --

![image](https://user-images.githubusercontent.com/6722114/29058077-483d5f34-7bc3-11e7-9c96-d8f594d5808d.png)

**Comment by nicolevasilevsky** [comment]
DO has an exact syn that xrefs the NCIT term
![image](https://user-images.githubusercontent.com/6722114/29092646-ed7128a0-7c3b-11e7-9e80-f68721a93ddb.png)

**Comment by cmungall** [comment]
Which DO class?

**Comment by cmungall** [comment]
OK, there is actually some stuff to fix with Orphanets xrefs here, but let's stick to DO for now

![image](https://user-images.githubusercontent.com/50745/29100946-df3bb980-7c63-11e7-9ecc-bf162fa460d4.png)

Note DO places tumor as a subclass of cancer. This causes probs when when we follow the DO xref and make equivalent to the malignancy-generic neoplasm in NCIT

```
   is_a NCIT:C4445 ! Pancreatic Exocrine Neoplasm
      is_a NCIT:C41247 ! Pancreatic Mucinous-Cystic Neoplasm
      is_a NCIT:C41248 ! Pancreatic Serous Neoplasm
      is_a NCIT:C4613 ! Benign Exocrine Pancreas Neoplasm <---- includes benign!
      is_a NCIT:C7412 ! Pancreatic Precancerous Condition
      is_a NCIT:C7430 ! Malignant Exocrine Pancreas Neoplasm
      is_a NCIT:C95505 ! Pancreatic Intraductal Neoplasm
      is_a NCIT:C95542 ! Pancreatic Acinar Cell Neoplasm
```

**Comment by nicolevasilevsky** [comment]
DOID_1795 tumor of exocrine pancreas

**Comment by nicolevasilevsky** [comment]
(in every case, I am referring to the DO class at the top of the ticket)
