### ISSUE TITLE
DOID:225 (syndrome) is merged with ANE syndrome

### ISSUE THREAD

**Issue by mwilliamson-healx** [monarch-initiative/monarch-disease-ontology-RETIRED#301]
The Disease Ontology term "syndrome" (DOID:225) has been merged with [ANE syndrome](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=157954). It seems to me that the merging of the DO term is erroneous.

**Comment by nicolevasilevsky** [comment]
Looks like this has been fixed, closing
