### ISSUE TITLE
Prostate cancer from DO is merged with familial prostate cancer from MeSH and Orphanet

### ISSUE THREAD

**Issue by mwilliamson-healx** [monarch-initiative/monarch-disease-ontology-RETIRED#302]
Prostate Cancer from DO (DOID:10283) is merged with familial prostate cancer from MeSH (C537243) and Orphanet (1331), but I wouldn't consider these equivalent. Is this merging intentional?

**Comment by cmungall** [comment]
See above for the linked DO ticket. DO causes a lot of issues with merging as it conflates neoplasm and cancer, and sometimes familiar and non-familial

**Comment by nicolevasilevsky** [comment]
Looks like this has been addressed, closing.
