### ISSUE TITLE
NCIT_C7702 Adult Hodgkin Lymphoma SubClassOf Hodgkin's granuloma

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#311]
NCIT_C7702 | Adult Hodgkin Lymphoma | SubClassOf | DOID_8651 | Hodgkin's granuloma
-- | -- | -- | -- | --

![image](https://user-images.githubusercontent.com/6722114/29097179-456baa56-7c4d-11e7-8bfd-c396c39f60fa.png)

**Comment by nicolevasilevsky** [comment]
I'm not sure about this one. The equivalence between DOID_8651 and the NCIT, Orphanet and OMIM seems like it could be incorrect?

![image](https://user-images.githubusercontent.com/6722114/29100409-2f6dbeac-7c60-11e7-9288-7f9a7e1edc17.png)

**Comment by pnrobinson** [comment]
Might be a useful reference
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=5&ved=0ahUKEwicpbu1h8nVAhVE7SYKHUvUCBEQFghDMAQ&url=http%3A%2F%2Fwww.hematology.org%2FClinicians%2FPriorities%2FDocuments%2F2749.aspx&usg=AFQjCNEY2JitXFopAVbwY7MriRI5HAAiNw

**Comment by cmungall** [comment]
We had some discussion related in #203 and #204

**Comment by nicolevasilevsky** [comment]
Is this correct? (this is based on #204)

![image](https://user-images.githubusercontent.com/6722114/29138082-5c222d4c-7cf7-11e7-98e2-a883a957a60e.png)

**Comment by nicolevasilevsky** [comment]
and based on Peter's doc (thanks @pnrobinson !), it seems that hodgkins granuloma and hodgkins lymphoma are distinct classes, so the proposed subclass relationship is incorrect, yes?

**Comment by pnrobinson** [comment]
?I am not an expert on HL, but I do believe they are distinct diagnoses.

-Peter


Peter Robinson

Professor of Computational Biology

The Jackson Laboratory for Genomic Medicine

10 Discovery Drive

Farmington, CT 06032

860.837.2095 t | 860.990.3130 m

peter.robinson@jax.org<mailto:peter.robinson@jax.org>

www.jax.org

Robinson lab: https://robinsongroup.github.io/

The Jackson Laboratory: Leading the search for tomorrow's cures

________________________________
