### ISSUE TITLE
NCIT_C9331	Malignant Gastric Neoplasm

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#313]
NCIT_C9331 | Malignant Gastric Neoplasm | SubClassOf | DOID_10534 | stomach cancer
-- | -- | -- | -- | --

![image](https://user-images.githubusercontent.com/6722114/29097205-7be1ee92-7c4d-11e7-8663-14f6fcd85392.png)

**Comment by nicolevasilevsky** [comment]
I think this is okay, as NCIT already asserts that subclass relationship.

**Comment by cmungall** [comment]
hmm, it's not quite correct to say that NCIT asserts that subclass relationship. It asserts a relationship between two NCIT concepts. The question is whether DOID gastric cancer is equivalent to NCIT gastric neoplasm.

I think the answer is no. neoplasm != cancer. The ncit class has benign subclasses.

```
  is_a NCIT:C3387 ! Gastric Neoplasm 
     is_a NCIT:C3599 ! Benign Gastric Neoplasm ***
     is_a NCIT:C3955 ! Gastric Intraepithelial Neoplasia
     is_a NCIT:C54094 ! Gastric Granular Cell Tumor
     is_a NCIT:C5487 ! Gastric Soft Tissue Neoplasm
     is_a NCIT:C5696 ! Gastric Neuroendocrine Neoplasm
     is_a NCIT:C6448 ! Gastric Germ Cell Tumor
     is_a NCIT:C7699 ! Gastric Adenoma
     is_a NCIT:C9331 ! Malignant Gastric Neoplasm
```

There are some things I find unusual with NCIT here, who should we tag?

e.g.
```
 is_a NCIT:C4890 ! Malignant Digestive System Neoplasm
   is_a NCIT:C9331 ! Malignant Gastric Neoplasm *** 
    is_a NCIT:C27439 ! Malignant Gastric Soft Tissue Neoplasm
    is_a NCIT:C4636 ! Gastric Lymphoma
    is_a NCIT:C4911 ! Gastric Carcinoma EXACT SYN: "gastric cancer"
 ```

why is the syn attached at this level, and not at MGN? I get the in the stomach carcinomas are more common that sarcomas so in common usage cancer means carcinoma most of the time.. but still seems odd and not very OBO-esque

I would be inclined to make DO GC = NCIT MGN

**Comment by nicolevasilevsky** [comment]
What do you mean by DO GC? Gastric carcinoma (DOID_5517)?

Is a malignant neoplasm = cancer?

**Comment by cmungall** [comment]
> What do you mean by DO GC? Gastric carcinoma (DOID_5517)?

yes

> Is a malignant neoplasm = cancer?

This makes sense to me, but I see some cases where distinct classes are present in NCIT. We need their design pattern docs!

**Comment by nicolevasilevsky** [comment]
Ok, does this picture summarize what you are thinking?
![image](https://user-images.githubusercontent.com/6722114/29134196-c76f70bc-7cea-11e7-9054-c1359ecbfcf4.png)

**Comment by nicolevasilevsky** [comment]
Should I be updated a curated ptable, like before?

And should I make those recommendations on the DO tracker?
