### ISSUE TITLE
NCIT_C7548 | Malignant Kidney Neoplasm 

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#315]
NCIT_C7548 | Malignant Kidney Neoplasm | SubClassOf | DOID_263 | kidney cancer
-- | -- | -- | -- | --

![image](https://user-images.githubusercontent.com/6722114/29097263-b4f3a266-7c4d-11e7-98a8-2a6041c421fc.png)

**Comment by nicolevasilevsky** [comment]
As long as we are okay with the equiv between kidney cancer (DO) and kidney neoplasm (NCIT), I think this is okay.

**Comment by cmungall** [comment]
sorry, big problems here, if we believe the equiv then we also believe that C4778 'benign KN' is a cancer. (Need those DPs documented!!!)

I'm a bit perplexed how it got this solution the disjointness axioms (#169) should have prevented this

**Comment by nicolevasilevsky** [comment]
@cmungall when you say you need the DPs documented, is this something you need from me or the NCIT team?

**Comment by nicolevasilevsky** [comment]
Is this what you are suggesting? In #313, we said that maybe malignant neoplasm = cancer.
![image](https://user-images.githubusercontent.com/6722114/29137391-12044bfc-7cf5-11e7-9cd8-a3bf4ad4b6db.png)
