### ISSUE TITLE
NCIT_C9311	Malignant Cervical Neoplasm

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#316]
NCIT_C9311 | Malignant Cervical Neoplasm | SubClassOf | DOID_4362 | cervical cancer
-- | -- | -- | -- | --

![image](https://user-images.githubusercontent.com/6722114/29097516-12db281c-7c4f-11e7-8eed-72b9c23024bd.png)

**Comment by nicolevasilevsky** [comment]
I think this is okay

**Comment by cmungall** [comment]
I don't think so :-[

neoplasm != cancer (sensu NCIT)
carcinoma != cancer (unless the tissue is entirely epithelial; if we consult NCIT we'll see that there are sarcomas in the stromal tissue of the cervix)

complicating the picture, what should our interpretation of https://omim.org/entry/603956 be? cancer or carcinoma? I would say based on the evidence about gene association carcinoma here but there is a deeper problem here, what DO are doing with susceptibility-of relations is fundamentally correct.

**Comment by cmungall** [comment]
On 9 Aug 2017, at 8:55, Nicole Vasilevsky wrote:

> Ok, I think I understand - what you are saying is there are issues 
> with the equivalences between DOID_4362 cervical cancer and NCIT_C2940 
> cervical neoplasm (and the MeSH term too)?

Yes

> From the definition of OMIM_603956 Cervical Cancer, I think they are 
> referring to carcinoma.

Yep, but OMIM is inherently vague with scope of terms like this

> In general though, DO maps their 'cancer' terms to NCIT 'neoplasm', so 
> this is a problem throughout, right?

I think it's a massive problem throughout though.

> In general, should we say the suggested subclass relationship between 
> an NCIT neoplasm as a child of a DOID cancer is incorrect then? Ie 
> NCIT_C9311 Malignant Cervical Neoplasm SubClassOf DOID_4362 cervical 
> cancer is wrong?

I would say this is correct. But ideally these decisions would be based 
on a design doc that clearly states the design patterns used in NCIT, 
rather than us inferring them. This would be a collaboration between 
NCIT and us. We would ideally have reciprocal docs in DO.

> There are some other similar tickets 
> ([#313](<https://github.com/monarch-initiative/monarch-disease-ontology/issues/313>), [#314](<https://github.com/monarch-initiative/monarch-disease-ontology/issues/314>), [#315](<https://github.com/monarch-initiative/monarch-disease-ontology/issues/315>)), 
> I'll revise my comments there.

**Comment by nicolevasilevsky** [comment]
Thanks! For the design patterns doc, can I help get this started? Can you give me more specifics as to how to get this started?

**Comment by nicolevasilevsky** [comment]
Should I start a google doc and add some notes from this thread and related threads?
