### ISSUE TITLE
NCIT_C3268	Nervous System Neoplasm

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#319]
NCIT_C3268 | Nervous System Neoplasm | SuperClassOf | DOID_3093 | nervous system cancer
-- | -- | -- | -- | --

![image](https://user-images.githubusercontent.com/6722114/29097694-16be3d6a-7c50-11e7-8c02-ed5a5554c163.png)

**Comment by nicolevasilevsky** [comment]
Does this seem correct?
![image](https://user-images.githubusercontent.com/6722114/29138853-bf782c96-7cf9-11e7-89cc-0913fbf54ce1.png)

**Comment by cmungall** [comment]
You also need to X out the equiv to the NPaSCN class, otherwise you infer equivalency between two NCITs (and biologically NPaSCN seems more specific than the others)

(but don't worry, kboom assigns zero probability to such a config, the Xs are sufficient to give kboom the cues it needs)
