### ISSUE TITLE
Get definitions

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#34]
_From @mellybelly on March 31, 2015 17:10_

As part of of the build we need to pull the definitions from DO, OMIM, and orphanet, with some order of priority. @nlwashington has built the OMIM and GeneReview text descriptions, these should be relatively easy to pull together with DO terms? then we could potentially identify terms with no definitions (eg. DC terms). 

_Copied from original issue: monarch-initiative/human-disease-ontology#25_

**Comment by nicolevasilevsky** [comment]
_From @cmungall on March 31, 2015 17:45_

http://nif-crawler.neuinfo.org/monarch/ttl/ 
genereviews.ttl has labels syns but not defs

**Comment by nicolevasilevsky** [comment]
_From @mellybelly on March 31, 2015 17:49_

I believe @nlwashington is working on licensing issues but hopefully soon defs too.

**Comment by nicolevasilevsky** [comment]
_From @nlwashington on March 31, 2015 20:56_

awaiting licensing from GR/UW Tech Transfer office.  hoping to have another call with them next week.

**Comment by nicolevasilevsky** [comment]
_From @nlwashington on April 6, 2015 23:5_

do you think we should try to get some kind of licensing for http://www.merckmanuals.com/#three ?

**Comment by nlwashington** [comment]
i've added defintions into the genereviews.ttl file now.  this should be integrated into the pipeline.
