### ISSUE TITLE
NCIT_C9325	Adrenal Cortex Carcinoma

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#351]
NCIT_C9325 | Adrenal Cortex Carcinoma | SubClassOf | DOID_660 | adrenal cortex cancer
-- | -- | -- | -- | --

![image](https://user-images.githubusercontent.com/6722114/29098859-833130aa-7c56-11e7-8b5a-4875bd2624eb.png)

**Comment by cmungall** [comment]
Related: https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/366
