### ISSUE TITLE
incorrect mapping between NCIT and DO: neoplasm !=cancer?

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#363]
There are many examples of DO terms mapped to NCIT, where they use 'cancer' in the label and NCIT uses 'neoplasm'. I think these mappings are incorrect. An example is below.

NCIT_C3528 | Malignant Hard Palate Neoplasm | EquivalentTo | DOID_9149 | hard palate cancer | 0.7905298989
-- | -- | -- | -- | -- | --

More examples are in this [spreadsheet](https://docs.google.com/spreadsheets/d/1dxXR43RlouVMd2bSmYD4po1lM12mWNKOIkC6gqddUjA/edit#gid=655687146).

Not sure if NCIT tumor terms should be mapped to DO cancer terms. An example is below.

NCIT_C7113 | Endometrioid Tumor | EquivalentTo | DOID_3001 | female reproductive endometrioid cancer
-- | -- | -- | -- | --

**Comment by cmungall** [comment]
It always helps to look at defs. The DO class has no def here, but properties of parent defs are inferred.

 * NCIT:C7113 ! Endometrioid Tumor ***  [DEF: "A __benign, borderline, or malignant__ epithelial tumor of the female reproductive system characterized by the presence of glands and/or cysts lined by neoplastic cells that resemble endometrial cells."]

The NCIT class is explicitly malignancy-neutral

```
    is_a DOID:162 ! cancer [DEF: "A disease of cellular proliferation >>>>>that is malignant<<<< and primary, characterized by uncontrolled cellular proliferation, local cell invasion and metastasis."]
     is_a DOID:0050686 ! organ system cancer [DEF: "A cancer that is classified based on the organ it starts in."]
      is_a DOID:193 ! reproductive organ cancer [DEF: "An organ system cancer that is manifested in the reproductive organs."]
       is_a DOID:120 ! female reproductive organ cancer [DEF: "A reproductive organ cancer that is manifested in the female genitals. This includes organs such as the ovaries, fallopian tubes, uterus, cervix, vagina and vulva."]
        is_a DOID:3001 ! female reproductive endometrioid cancer
```
