### ISSUE TITLE
NCIT_C3200 | Lung Neoplasm mapping

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#365]
Not sure if this mapping is correct, but I think it may be okay. Depends on how cancer should be mapped to NCIT.

NCIT_C3200 | Lung Neoplasm | SuperClassOf | DOID_1324 | lung cancer | 0.7999715434
-- | -- | -- | -- | -- | --

![image](https://user-images.githubusercontent.com/6722114/29229933-a4ad3a3a-7e95-11e7-8ee2-c1b622d1735b.png)

**Comment by cmungall** [comment]
Yes, I agree. As this was given a high probability and your evaluation agrees we don't need to make a ticket for all of these.

However, since we have this open, it's worth looking at the bottom left there. Note the low probability placement of the MESH term. I would have made this equivalent. I'm trying to figure why this wasn't done...

**Comment by cmungall** [comment]
so mesh place nscLC as a subtype of bronchogenic:

```
   is_a MESH:D002283 ! Carcinoma, Bronchogenic
      is_a MESH:D002289 ! Carcinoma, Non-Small-Cell Lung *** 
```

in NCIT they are direct sibs:

![image](https://user-images.githubusercontent.com/50745/29233572-94ca0a1a-7ea6-11e7-8f5e-9f6af7366ae8.png)

I am generally inclined to trust NCIT over MESH. I suspect MESH is doing it this was as many nscLCs do arise in peripheral tissue, but yet they are wrong to classify it this way as there are exceptions?

In DO, they are more distant sibs:

![image](https://user-images.githubusercontent.com/50745/29233592-c4946bdc-7ea6-11e7-99b4-4e8fb59d35f2.png)

This highlights an issue with strict location based classification: the bronchus is typically not considered part of the lung. bronchiogenic carcinoma arises in the epithelium of bronchus/iole and migrates to the lung
