### ISSUE TITLE
NCIT_C46099 Benign Intestinal Neoplasm

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#369]
I think NCIT_C46099 and DOID_4610 should be equiv

NCIT_C46099 | Benign Intestinal Neoplasm | SubClassOf | DOID_4610 | intestinal benign neoplasm | 0.2592103492
-- | -- | -- | -- | -- | --

![image](https://user-images.githubusercontent.com/6722114/29235820-82ed7c30-7eb7-11e7-8270-f92730e0ecd9.png)

**Comment by nicolevasilevsky** [comment]
The NCIT ID is wrong in the spreadsheet, it should be NCIT_C4609

**Comment by cmungall** [comment]
The spreadsheet was created automatically how did this happen? It's possible I could have hit a key when scrolling through at some point? One reason I like git and explicit commits...
