### ISSUE TITLE
check 'not inherited' children in ordo

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#388]
ordo does not have a tracker so I'm placing this here, cc @annieolry 

'not inherited' in OLS
http://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_409941

see "Related from: 
has_inheritance" in the side panel

Many of these look like diseases or phenotypes that are either always inherited or at least potentially inherited:

 * 49,XXXXY syndrome
 * MODY
 * cleft palate

See for example on the MODY page http://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_552

![image](https://user-images.githubusercontent.com/50745/29583980-233f472c-8737-11e7-9aff-5fedecea3adf.png)

it has two axioms

 * subClassOf 'has inheritance' some AS
 * subClassOf 'has inheritance' some 'not inherited'

this is surely a contradiction

cc @SimonJupp

**Comment by nicolevasilevsky** [comment]
closing, I think this is resolved
