### ISSUE TITLE
breast papillary carcinoma

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#389]
![image](https://user-images.githubusercontent.com/50745/29593278-4c98a6b4-875e-11e7-883a-4fabf6ca3cb0.png)

note NCIT has 

```
       is_a NCIT:C9134 ! Papillary Breast Carcinoma 
           is_a NCIT:C36085 ! Invasive Papillary Breast Carcinoma
           is_a NCIT:C4190 ! Intraductal Papillary Breast Carcinoma
           is_a NCIT:C6870 ! Solid Papillary Breast Carcinoma
```

the DOID is xreffed to the subclass ('solid')

```
[Term]
id: DOID:5592
name: breast papillary carcinoma
namespace: disease_ontology
alt_id: DOID:6800
synonym: "Papillary carcinoma of the breast" EXACT [NCI2004_11_17:C9134]
synonym: "breast solid papillary carcinoma" EXACT []
synonym: "papillary carcinoma of breast" RELATED []
synonym: "solid papillary carcinoma of the breast" RELATED []
xref: NCI:C6870
xref: UMLS_CUI:C1336027
is_a: DOID:3113  ! papillary carcinoma
is_a: DOID:3459  ! breast carcinoma
```

without a DO definition it's not clear what this is intended to be. The synonyms indicate conflation between what NCIT considers different classes

**Comment by nicolevasilevsky** [comment]
I marked this as undecided in our [spreadsheet](https://docs.google.com/spreadsheets/d/1dxXR43RlouVMd2bSmYD4po1lM12mWNKOIkC6gqddUjA/edit#gid=655687146).

**Comment by nicolevasilevsky** [comment]
is there any other action required for this?

**Comment by nicolevasilevsky** [comment]
I think this has been resolved, closing
