### ISSUE TITLE
Unexpected cross reference

### ISSUE THREAD

**Issue by mwilliamson-healx** [monarch-initiative/monarch-disease-ontology-RETIRED#390]
One of the diseases (OMIM:251290) has an unexpected cross reference of:

```
An autosomal recessive disease that is characterized by  congenital microcephaly, intracranial calcifications, severe developmental delay, simplified gyration and polymicrogyria, and severe developmental delay.
```

Presumably this is an error?

**Comment by nicolevasilevsky** [comment]
@mwilliamson-healx, Is this still an issue? I'm not sure what the unexpected xref is.

**Comment by nicolevasilevsky** [comment]
Closing. If this is still an issue, please reopen on the new tracker:
https://github.com/monarch-initiative/mondo/issues
