### ISSUE TITLE
autoimmune retinopathy

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-disease-ontology-RETIRED#391]
we don't seem to have this as a disease, see for example:

http://www.ohsu.edu/xd/health/services/casey-eye/clinical-services/specialty-services/genetics/autoimmune-retinopathy.cfm

see also relationships to cancer described there. 

There is also a patient group on Facebook: https://www.facebook.com/groups/AIRcommunity/
(we really should be working with Facebook....)

**Comment by nicolevasilevsky** [comment]
This issue was moved to monarch-initiative/mondo#165
