### ISSUE TITLE
hyperlysinemia subtypes

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#396]
Background (from OMIM): *Saccharopinuria, also known as hyperlysinemia type II, is an autosomal recessive metabolic condition with few, if any, clinical manifestations. Hyperlysinemia type II and hyperlysinemia type I (238700) both result from deficiency of the bifunctional enzyme AASS (605113) on chromosome 7q31*

This is the current version of MonDO:

![image](https://user-images.githubusercontent.com/50745/30860242-5be76a50-a27b-11e7-9bb6-d5ed384c15a0.png)

as tree:

```
     is_a DOID:9274 ! hyperlysinemia *** 
         is_a MESH:C563201 ! Lysine Intolerance
         is_a MESH:C565499 ! Hyperlysinemia Due To Defect In Lysine Transport Into Mitochondria
         is_a OMIM:238700 ! Hyperlysinemia, Type 1
         is_a OMIM:238710 ! Hyperlysinemia Due to Defect 1N Lysine Transport Into Mitochondria
         is_a OMIM:268700 ! Saccharopinuria [AKA hyperlysinemia type 2]
```

Note that MESH:C565499 and OMIM:238710 failed to merge, perhaps due to the weird "1N" being introduced into our pipeline

MESH causes various kinds of issues, so we're experimenting with dropping it out. This results in the grouping between hyperlysinemia type 2 and type 1 being lost as no other resource makes the connection.

Orphanet has:

```
    is_a Orphanet:289832 ! Disorder of lysine and hydroxylysine metabolism *** 
       po Orphanet:2203 ! Hyperlysinemia [xref: OMIM:238700, OMIM:238710]
       po Orphanet:3124 ! Saccharopinuria [xref: OMIM:268700]
       po Orphanet:79154 ! 2-aminoadipic 2-oxoadipic aciduria  [xref: OMIM:204750]
       po Orphanet:79156 ! Seizures-intellectual disability due to hydroxylysinuria syndrome [xref: OMIM:236900]
```

i.e. they treat the name  Hyperlysinemia as being type I, plus the mito transport one, and they have Saccharopinuria/type II as a sibling, but with a more general grouping

GHR groups both type I and II into a general term: https://ghr.nlm.nih.gov/condition/hyperlysinemia

**Comment by nicolevasilevsky** [comment]
I think this has been resolved, closing.
