### ISSUE TITLE
EFO classifies Chronic Fatigue Syndrome as a mental/behavioral disorder 

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#398]
http://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0004540

This is not in line with current thinking, I can provide refs if need be

**Comment by siiraa** [comment]
@cmungall syndrome is hard to classify. Will really appreciate any classification pointer. thank you :)

**Comment by cmungall** [comment]
@siiraa - my primary objection was the placement under 'mental or behavioral disorder'

![image](https://user-images.githubusercontent.com/50745/31846414-1feea5e2-b5c0-11e7-9c94-6caa55dd0624.png)

I also think the 'muscular disease' is problematic

@pnrobinson 

I have changed the name as you suggest.

I think we should describe the neurological and behavioral manifestations, but this can be done in annotations to HPO rather than hardwiring is-a in the ontology. I like the idea of constitutional disease. For now we have 'syndromic disease' as the sole parent class in mondo, which is not wrong but could be improved?

What would you make of immune system disease? It seems a lot of recent research is pointing in this direction? Or should we record hypotheses outside the ontology in annotations?

**Comment by pnrobinson** [comment]
In fact we will be doing research on ME/CFS at JAX and our hypothesis is that it is in part an immune mediated disorder. But I would say that there is not sufficient evidence to state this as a fact in a disease ontology, and I would prefer to be non-committal as to the etiology. It is also very likely that ME/CFS is quite heterogeneous etiologically, and thus probably it will be stratified in ways that are hard to predict today.

**Comment by nicolevasilevsky** [comment]
closing, I think this is resolved
