### ISSUE TITLE
Camurati-Engelmann disease types 1 and 2

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#399]
we make the call:

 * OMIM_131300 Camurati-Engelmann Disease SubClassOf Orphanet_1328 Camurati-Engelmann disease Pr= 0.08695652173913043

note the low probability. kboom is rightly flagging an issue here. Orphanet calls these as equivalent and doesn't acknowledge OMIM_606631 Camurati-Engelmann Disease, Type 2

However, if type 2 exists the correct thing to do is to group t1 and t2 under a superclass

https://en.wikipedia.org/wiki/Camurati%E2%80%93Engelmann_disease#Classification

"Type 2 Camurati-Engelmann Disease is still speculative, with no distinct evidence to credit its existence. There are many similarities between Type 2 CED and hyperostosis generalisata with striations of the bones (HGS), with some speculating they are two phenotypic variations of the same disease"

https://omim.org/clinicalSynopsis/606631

no phenotypes in hpoa

**Comment by pnrobinson** [comment]
Cases like this are a hard call. Even though the case report got an OMIM number, it is still a relatively questionable one-off report and without more reports it is hard to say of there truly are two types of CES. Previously, OMIM was much more lenient with n+1 reports (this publication is from 2002!), and this certainly would not have warranted a separate OMIM id today. This is one of the things that really needs to be cleaned up in OMIM -- it at least needs a flag that it is n=1. We should try to do better in MONDO!

**Comment by nicolevasilevsky** [comment]
This issue was moved to monarch-initiative/mondo#163
