### ISSUE TITLE
Mobius misspelled

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#4]
Möbius, which is also spelled Moebius should not be Mobius.
http://monarchinitiative.org/disease/OMIM_157900
I believe it is wrong in a number of places including NCI, DO, and MESH.

From: https://github.com/monarch-initiative/monarch-app/issues/588

**Comment by nicolevasilevsky** [comment]
This issue was moved to monarch-initiative/mondo#168
