### ISSUE TITLE
Hypotrichosis-Lymphedema-Telangiectasia Syndrome - with/without renal

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#401]
kboom splits the orpha into two omim subclasses:

![image](https://user-images.githubusercontent.com/50745/31027989-24ead0f4-a501-11e7-9921-a31ce44bd151.png)

This is backed up by the orphanet ntbt calls, and biologically justified (the two forms are both SOX18, het vs hom), but this seems to be one of those prototype cases (#149), note the similarity in name between the renal form and the orphanet grouping.

It doesn't seem quite right to name the grouping with the renal phenotype. Not clear what the name of the grouping should be.

other info:
https://rarediseases.info.nih.gov/diseases/12827/hypotrichosis-lymphedema-telangiectasia-syndrome

this is how our HPOA annotations are distributed:

![image](https://user-images.githubusercontent.com/50745/31031648-0bf5cc4a-a50e-11e7-8f72-c229fa0c6f96.png)

**Comment by nicolevasilevsky** [comment]
this looks like it has been fixed in MONDO
