### ISSUE TITLE
EFO has ornithine carbamoyltransferase deficiency isa tuberculosis

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#404]
![image](https://user-images.githubusercontent.com/50745/31047919-35d1c62e-a60b-11e7-91a4-d6e86322ff73.png)

It looks like this got mixed up with the term to represent genital tuberculosis.

**Comment by siiraa** [comment]
reclassified under urogential tuberculosis. This issue is resolved now.

**Comment by pnrobinson** [comment]
what does this have to do with urogenital TB?

**Comment by cmungall** [comment]
@siiraa - I agree with @pnrobinson I think this is a mistake

**Comment by nicolevasilevsky** [comment]
this looks like it is fixed in MONDO, so I am closing
