### ISSUE TITLE
ORDO: Autosomal dominant non-syndromic intellectual disability is classified as etiological subtype

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#407]
https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_178469

![image](https://user-images.githubusercontent.com/50745/31587867-211e100e-b19e-11e7-8bef-9d0e2d7156db.png)

This throws us off a bit as we give lower prior weights to classifying diseases under etiological subtypes

I think this is something unique to ORDO, as it doesn't seem to be in the source orphanet? http://orpha.net/consor/cgi-bin/OC_Exp.php?Expert=377795

cc @annieolry

**Comment by cmungall** [comment]
Same for AR:

https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_88616

nothing here:
http://orpha.net/consor/cgi-bin/OC_Exp.php?Expert=88616

**Comment by siiraa** [comment]
Hi, 
This is the ORDO issue at source, we do not have control over it. This same term in EFO, as we imported it a few years ago, is asserted under 'Rare intellectual disability without developmental anomaly' only. See https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_178469 .

We can fix anything that we import into EFO, but if it is at source that needs to be fixed, we'd have to contact Orphanet directly.

**Comment by nicolevasilevsky** [comment]
closing, looks like this was fixed
