### ISSUE TITLE
ORDO: X-linked nonsyndromic deafness

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#408]
Similar to #407 

This one also dubious:

https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_90625

![image](https://user-images.githubusercontent.com/50745/31587918-148db71c-b19f-11e7-9158-c6c99dd27141.png)

Another issue is dual classification under prelingual and postlingual:

![image](https://user-images.githubusercontent.com/50745/31587921-21555630-b19f-11e7-9bb3-ee40d33a7c07.png)

This one also not found here: http://orpha.net/consor/cgi-bin/OC_Exp.php?Expert=90625

obsoleted?

cc @annieolry

**Comment by pnrobinson** [comment]
One further issue here is that DFN itself is not meaningful as an abbreviation (AFAIK), it should be further specified. See https://www.ncbi.nlm.nih.gov/books/NBK1434/

**Comment by siiraa** [comment]
What EFO imported in has the classification as seen here - https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_90625

If ORDO has a fix that we should reflect in EFO, please let us know. Thank you.

**Comment by nicolevasilevsky** [comment]
this looks like it was fixed

**Comment by cmungall** [comment]
This coming up again

I don't think it makes sense to equivalenceify

https://omim.org/phenotypicSeries/PS304500

and

https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_90625

The ordo class is for nonsyndromic forms

the PS has syndromic forms, e.g. https://omim.org/entry/301018

which in ordo is https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_500188

**Comment by nicolevasilevsky** [comment]
Sounds like we should split these terms in Mondo? I'll create a ticket in the new Mondo tracker
