### ISSUE TITLE
rhabdoid cancer

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#409]
kboom makes a poor solution here, in part confused by:

![image](https://user-images.githubusercontent.com/50745/31699903-8ba06d2c-b37a-11e7-849c-a6eb815e8ca8.png)

while rhabdoid cancers are frequently in the kidney, it can also arise from other tissue. use NCIT here.

**Comment by nicolevasilevsky** [comment]
this looks like it was fixed
