### ISSUE TITLE
Orphanet disease IDs without classification and not in ORDO

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#413]
This ticket lists IDs in the orphanet database but lacking classification and hence not in ordo. We will decide on a case by case basis whether these should be made equivalent to other IDs

 * http://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=279 Age-related macular degeneration

**Comment by nicolevasilevsky** [comment]
@cmungall can this be closed?
