### ISSUE TITLE
Genetic hypertension is_a renal disease?

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#414]
ordo has this:

https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_156629

![image](https://user-images.githubusercontent.com/50745/31869024-eed1bc2e-b759-11e7-97ef-669e504ea1e9.png)

It seems that the kidney can play a role in pathogenesis of genetic hypertension
http://hyper.ahajournals.org/content/46/3/463

and can be affected
http://www.nature.com/jhh/journal/v28/n2/full/jhh201355a.html

bookmarked interesting discussion of hypertensive kidney disease
http://jasn.asnjournals.org/content/19/11/2047.full

Regardless, should this association be hardwired via a SubClassOf in the ontology?

Are all the child terms of this really renal diseases? E.g.

https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http://www.orpha.net/ORDO/Orphanet_99819

**Comment by nicolevasilevsky** [comment]
This issue was moved to monarch-initiative/mondo#154
