### ISSUE TITLE
ORDO constitutional vs acquired alplastic anemia

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#415]
Consider: https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_68383

![image](https://user-images.githubusercontent.com/50745/31903435-ee79615e-b7dc-11e7-940d-54b5ad0cdc48.png)

Aplastic anemia is already classified under 'rare constitutional anemia'. This means that every instance of Aplastic anemia is an instance of 'rare constitutional aplastic anemia'. Which would render the distinct class RCAA superfluous - and its sibling 'rare acquired aplastic anemia' unsatisfiable.

**Comment by nicolevasilevsky** [comment]
This issue was moved to monarch-initiative/mondo#153
