### ISSUE TITLE
Self loop for MONDO:0010765

### ISSUE THREAD

**Issue by drseb** [monarch-initiative/monarch-disease-ontology-RETIRED#418]
I think this is wrong!?

```
[Term]
id: MONDO:0010765
name: 46,XY complete gonadal dysgenesis
...
is_a: MONDO:0010765 {source="OMIM:400044"} ! 46,XY complete gonadal dysgenesis

```

**Comment by drseb** [comment]
I know, formally, this is not wrong, but still might point towards a "optimisable" part of the generation pipeline.

**Comment by nicolevasilevsky** [comment]
MONDO:0010765 has been obsoleted, so I think this has been fixed. Please reopen if not.
