### ISSUE TITLE
Move issues from here to new repo, or close them

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#425]
This repo was for the original automatic MONDO. Many of the issues raised have been addressed in the curated version. We should go through, close any not relevant, and move any still relevant, using gh issue mover

**Comment by nicolevasilevsky** [comment]
I'm on it!
The issue mover is really cool, I have never used it before. :)

**Comment by nicolevasilevsky** [comment]
Done! (And I realized I have actually used the issue move before, ignore my comment above!)
