### ISSUE TITLE
add mappings to OMIM phenotypic series

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#5]
_From @nlwashington on March 6, 2015 17:25_

we can use the phenotypic series from OMIM as some grouping classes.  The phenoseries ids are part of the omim file, here:
http://nif-crawler.neuinfo.org/monarch/ttl/omim.ttl

see ticket here:
https://github.com/obophenotype/human-disease-ontology/issues/25

_Copied from original issue: monarch-initiative/human-disease-ontology#1_

**Comment by nicolevasilevsky** [comment]
I think this can be closed.
