### ISSUE TITLE
Place OMIM traits into distinct file

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#53]
For original discussion see: https://github.com/monarch-initiative/monarch-app/issues/955

Various IDs such as "Skin/Hair/Eye Pigmentation, Variation In, 9" OMIM:611742 are in the omimexclude file maintained by @sbello - this is good, as these are not diseases.

However, we have some data associated with this OMIM ID, treating it as a trait. We should find a way to include these in a separate trait ontology.

**Comment by cmungall** [comment]
I'm not even 100% sure how to interpret the omim term

http://www.omim.org/entry/611742

it says "dark/light" hair. Does the omim term represent the trait (attribute) or the phenotype (value)?

**Comment by pnrobinson** [comment]
OMIM provides incomplete coverage of a number of traits that have been studied by GWAS. Especially, but not only, eQTL data from model organisms data can probably be mapped to this, but we will need to find a way to ingest data from GWAS Catalog and or GWAS Central and also to disambiguate traits and diseases (neither OMIM nor the GWAS databases reliably distinguish between disease and trait data!). Something to discuss at the upcoming strategy meeting!

**Comment by mellybelly** [comment]
Ontology of Biological Attributes !!
Also needed to support clinical measures such as in PhenX.

**Comment by mellybelly** [comment]
P.S. we should relate this set back to OMIM, has anyone done that? @sbello?

**Comment by jmcmurry** [comment]
This is a blocker for https://github.com/monarch-initiative/monarch-disease-ontology/issues/53

**Comment by nicolevasilevsky** [comment]
This issue was moved to monarch-initiative/mondo#194
