### ISSUE TITLE
omia diseases missing in mondo

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-disease-ontology-RETIRED#55]
We seem to be missing the OMIA diseases.

for example:  OMIA:000670 is not classified as a disease.  when i go to the monarch page for it, 
http://localhost:8080/disease/OMIA:000670
it doesn't show up with a label, nor does it have any annotations.  the missing annotations are now not surprising because it's not considered a disease.

i can certainly classify all the OMIA disease ids as a DOID:4, but you will probably want to integrate these into the pipeline better.  i thought we had these?  you could use the omia.ttl file that has some of the hierarchy in it, along with OMIM equivalences and xrefs, if you'd like.

**Comment by mellybelly** [comment]
![img_4695](https://cloud.githubusercontent.com/assets/796636/11224176/7fb55a2e-8d28-11e5-90f9-79d0b57b98bd.JPG)

here is the plan

**Comment by kshefchek** [comment]
We seem to have lost these in the latest load, for example: 

https://scigraph-ontology.monarchinitiative.org/scigraph/graph/neighbors?id=OMIA%3A000328&depth=1&blankNodes=false&relationshipType=subClassOf&direction=OUTGOING&entail=false&project=*

OMIA:000328 is a direct subclass of owl:Thing, and therefore not categorized as a disease
