### ISSUE TITLE
Renal disease with cataract not a renal disease

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-disease-ontology-RETIRED#56]
It would seem that Orphanet:98646 is not classified as a renal disease:
http://localhost:8080/disease/Orphanet:98646

**Comment by cmungall** [comment]
This is what the source ontology (ORDO) says:

![rdwc](https://cloud.githubusercontent.com/assets/50745/10549841/614d6e8a-73f8-11e5-8079-e10e0284a6bc.png)

see also http://www.orpha.net/consor/cgi-bin/Disease_Classif_Simple.php?lng=EN&LnkId=13663&Typ=Pat&diseaseType=Pat&from=rightMenu

not sure what to do about this. The orphanet classifications don't make sense to me a lot of the time
