### ISSUE TITLE
Rasopathy

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-disease-ontology-RETIRED#58]
we need a new term that may encompass Noonan syndrome, CFC, and Costello in cases when the submitting lab doesn’t have enough phenotypic information to distinguish between syndromes. After discussing with the Noonan group in ClinGen, it sounds like "Rasopathy" would be a request for this purpose. 

@cmungall @pnrobinson

**Comment by pnrobinson** [comment]
Rasopathy is the going term, +1

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor of Bioinformatics, Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson
________________________________
Von: Melissa Haendel [notifications@github.com]
Gesendet: Samstag, 14. November 2015 00:43
An: monarch-initiative/monarch-disease-ontology
Cc: Robinson, Peter
Betreff: [monarch-disease-ontology] Rasopathy (#58)


we need a new term that may encompass Noonan syndrome, CFC, and Costello in cases when the submitting lab doesn’t have enough phenotypic information to distinguish between syndromes. After discussing with the Noonan group in ClinGen, it sounds like "Rasopathy" would be a request for this purpose.

@cmungall<https://github.com/cmungall> @pnrobinson<https://github.com/pnrobinson>

**Comment by nicolevasilevsky** [comment]
this term has been added: MONDO_0021060
