### ISSUE TITLE
Consider adding human taxon info for human diseases

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-disease-ontology-RETIRED#59]
In order to separate out animal diseases from human ones we'll probably also need to append human taxon info in MONDO for OMIM, Orphanet, DO, etc.

**Comment by jmcmurry** [comment]
@nicolevasilevsky perhaps it is time to revisit this? It is causing some issues on the UI side.

**Comment by jmcmurry** [comment]
@kshefchek says we could script this in pretty easily.

**Comment by nicolevasilevsky** [comment]
What needs to be done? How can I help?

**Comment by jmcmurry** [comment]
Ultimately, MONDO will have both human and other animal diseases. So that means each class needs a taxon.

**Comment by cmungall** [comment]
can you make a ticket in the new tracker?

**Comment by nicolevasilevsky** [comment]
done!
