### ISSUE TITLE
add mappings ORDO and DO

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#6]
_From @nlwashington on March 6, 2015 17:27_

 Add mappings between ORDO and DO. 

see https://github.com/obophenotype/human-disease-ontology/issues/15 

_Copied from original issue: monarch-initiative/human-disease-ontology#2_

**Comment by cmungall** [comment]
_From @nlwashington on March 6, 2015 17:39_

We need orphanet disease ids properly added and xrefed/equivanced with the DOID.

There are a couple of relevant files:

The Orphanet rare disease ontology:
http://www.orphadata.org/cgi-bin/inc/ordo_orphanet.inc.php

Diseases cross-referenced with other nomenclatures:
http://www.orphadata.org/cgi-bin/inc/product1.inc.php

**Comment by cmungall** [comment]
Currently making use of the xrefs that are in 
http://www.orphadata.org/data/ORDO/ordo_orphanet_1.2.owl.zip

I have not checked this OWL against the sources they were presumably 
auto-generated from.

As a spot check, the OWL has references to 8289 distinct OMIM IDs (9228 
xrefs overall).

**Comment by nicolevasilevsky** [comment]
I think this can be closed
