### ISSUE TITLE
curation of OMIA within mondo

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-disease-ontology-RETIRED#61]
the addition of OMIA into MONDO likely needs some curation.  i have created many xrefs for the OMIA diseases to OMIM ids, and there are some clustering nodes, but the majority of OMIA diseases are going to be stuck under the DOID:4 (generic disease) node.

i think many of these diseases (there are <1700) will be able to be reclassified easily based on either the disease label or the xrefs associated with them.  

@cmungall or @mellybelly to advise.

**Comment by mellybelly** [comment]
@cmungall these should go in bridge file correct?
If @nicolevasilevsky puts them under their proper parent there, i think we should be good. It looks like there are many with OMIA xrefs that are subclasses of 'disease' now.

**Comment by cmungall** [comment]
not we'd be breaking any ontological commitment that the DO class represents the human disease. Also this would have some effects on various behaviors. 

For example, if OMIA:x goes unded OMIM:y, then when on the page for OMIM:y, the animal phenotypes will be shown and used to generate a profile for the owlsim search.

A safer approach would be to make the OMIAs parallel the OMIM with a different relationship. To avoid flatness we would make the disease hierarchy display also traverse over the homology relationships.

**Comment by mellybelly** [comment]
ok, but i think some have both OMIM and OMIA xrefs...

**Comment by mellybelly** [comment]
ok so...create a new animal disease file for all classes that have an OMIA xref, adding the homologous_to relationship to the parent disease (if it is also a human disease). If not also a human disease, it becomes a child of a new class "animal disease"?

Q: should we have a bridge file for the OMIA animal diseases and then classify them under DO diseases?
OR
could autoclassify under high level anatomical groupings that are new "animal diseases" or DO diseases
OR
some combination?

**Comment by cmungall** [comment]
safest to place them under existing nodes, to prevent excessive equivalence collapsing

OR curate true equivalences from initially xref and label seeded set
