### ISSUE TITLE
structured annotations

### ISSUE THREAD

**Issue by overbyc** [monarch-initiative/monarch-disease-ontology-RETIRED#64]
I'd like to be able to specify a query of symptoms associated with diseases. For diseases with "has_symptom" as an annotation, can those be specified in a structured form with an associated HP ID? 

For example, looking at annotations under DOID_0050012 in mondo.owl we see:

```
<obo:IAO_0000115 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">A viral infectious disease that results_in infection located_in joint, has_material_basis_in Chikungunya virus, which is transmitted_by Aedes mosquito bite. The infection has_symptom fever, has_symptom arthralgia, and has_symptom maculopapular rash.</obo:IAO_0000115> 
```

In this case, it would be helpful for "fever", "arthralgia" and "maculopapular rash" to be specified with their associated HP ids. 

Thanks for considering!

**Comment by cmungall** [comment]
Hi Casey,

Currently we keep the phenotype associations outside the ontology. However, we may revisit this for certain defining phenotypes for high level diseases (e.g. "neurodegenerative disease").

Our focus has not been infectious diseases though, thus far.

A while ago I parsed out all of these text descriptions in the DO and added them as separate OWL axioms. The idea was that these would be maintained as part of the main DO. I'm not sure where they are in their axiomatizing process, I'll take a look later...
