### ISSUE TITLE
missing connections in musculoskeletal diseases

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-disease-ontology-RETIRED#67]
I'm here for autoimmune disease of musculoskeletal system ([DOID:0060032](http://monarchinitiative.org/disease/DOID:0060032)) and it is not related in any way to Rheumatoid Arthritis ([OMIM:180300](http://monarchinitiative.org/disease/OMIM:180300)), nor even generally to musculoskeletal system disease ([DOID:17](http://monarchinitiative.org/disease/DOID:17)).  These connections should get added.

**Comment by cmungall** [comment]
Will probably have to be fixed at source in DOID.

According to
https://en.wikipedia.org/wiki/Autoimmune_disease#Autoimmune_Diseases

Strong evidence for placing [DOID:7148](http://purl.obolibrary.org/obo/DOID_7148) ! rheumatoid arthritis

under

[DOID:1557](http://purl.obolibrary.org/obo/DOID_1557) ! hypersensitivity reaction type III disease

but it's a weird table, juvenile RA is *not* in the same category, but by our way of thinking it's a *subtype* of RA
