### ISSUE TITLE
Parkinsons 15 subclassing

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-disease-ontology-RETIRED#68]
We have two disease terms in Monarch:

Parkinson Disease 15, Autosomal Recessive Early-Onset (OMIM:260300, MESH:C538104)
and
autosomal recessive early-onset Parkinson disease 15 (DOID:0060372, Orphanet:171695)

The former is as subclass of the latter.  Is this correct?

**Comment by pnrobinson** [comment]
It seems that the label of the Orphanet class is incorrect
http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=171695
but the OMIM entries listed on the site should be subclasses, I think!
-Peter

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor of Bioinformatics, Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson
________________________________
Von: Kent Shefchek [notifications@github.com]
Gesendet: Dienstag, 9. Februar 2016 18:30
An: monarch-initiative/monarch-disease-ontology
Betreff: [monarch-disease-ontology] Parkinsons 15 subclassing (#68)


We have two disease terms in Monarch:

Parkinson Disease 15, Autosomal Recessive Early-Onset (OMIM:260300, MESH:C538104)
and
autosomal recessive early-onset Parkinson disease 15 (DOID:0060372, Orphanet:171695)

The former is as subclass of the latter. Is this correct?

**Comment by cmungall** [comment]
Peter, can you clarify what you meant about the orphanet label?
