### ISSUE TITLE
add medgen disease id mappings

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#8]
_From @nlwashington on March 6, 2015 17:37_

please add medgen ids to the uberdisease ontology for xrefs.  these will be useful for linking with clinvar data.
http://www.ncbi.nlm.nih.gov/medgen/docs/faq/#rel

also found this possibly relevant:
ftp://ftp.ncbi.nih.gov/pub/medgen/MedGen_HPO_OMIM_Mapping.txt.gz

ftp://ftp.ncbi.nih.gov/gene/DATA/mim2gene_medgen

also see related https://github.com/monarch-initiative/disease-miner/issues/5
and https://support.crbs.ucsd.edu/browse/NIF-11766

_Copied from original issue: monarch-initiative/human-disease-ontology#4_

**Comment by cmungall** [comment]
_From @nlwashington on March 6, 2015 17:40_

Also note that the medgen-to-omim (and other vocab) mappings here can't be trusted as equivalence classes. For example, for Hermasky-Pudluck syndrome,
http://beta.neuinfo.org/mynif/search.php?q=DOID_3753&dis=Hermansky-Pudlak%20syndrome&t=indexable&nif=nlx_151671-4&b=0&r=20
it has several subtypes; each one maps to GeneReviews:NBK1287, which is for a general type of Hermansky-Pudlak.

**Comment by cmungall** [comment]
_From @mellybelly on March 6, 2015 17:46_

yeah i think i would want to manually review all medgen xrefs...

**Comment by mellybelly** [comment]
I think we do need to get the medgen mappings in somehow. Maybe they can be added as xrefs until we have further processes to properly deal with inconsistencies?

**Comment by cmungall** [comment]
Hmm, is it really the case that the only way to get the medgen native UIDs (not CUIs or fake CUIs) is from the enormous medgen_pubmed_lnk.txt.gz file?

**Comment by nlwashington** [comment]
What about the MGDEF.RFF ?

**Comment by nlwashington** [comment]
(ftp://ftp.ncbi.nih.gov/pub/medgen/README.html)
