### ISSUE TITLE
Review classification of Osteogenesis Imperfecta, Type I in MonDO

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#89]
http://purl.obolibrary.org/obo/OMIM_259420

![image](https://cloud.githubusercontent.com/assets/6722114/15757998/42b58c94-28bd-11e6-96e1-2fd2510f2ed1.png)

**Comment by cmungall** [comment]
You can also attach the image directly

**Comment by nicolevasilevsky** [comment]
@cmungall, oh, I didn't realize that, thanks!

**Comment by nicolevasilevsky** [comment]
![image](https://cloud.githubusercontent.com/assets/6722114/16397637/83af2b58-3c7a-11e6-8365-24119d037383.png)

I think Orphanet_216796 and OMIM_166230 are equivalent, because the OMIM term xrefs this Oprhanet term.

**Comment by nicolevasilevsky** [comment]
I think that is the only issue with this one, everything else looks okay to me.

**Comment by pnrobinson** [comment]
OMIM_166230 is a "historical" OMIM entry that describes only one family and comes from a publication from 1981. The fact that this family did not have fractures means that they did not have OI type I, and thus the entries are not synonymous. However, it is possible to know exactly what this family had and there is certainly no syndrome (recognisable pattern of abnormalities that occurs in multiple families), and thus we should delete this entry for the purposes of MONDO.

**Comment by nicolevasilevsky** [comment]
Thanks @pnrobinson!

**Comment by cmungall** [comment]
> I think Orphanet_216796 and OMIM_166230 are equivalent, because the OMIM term xrefs this Oprhanet term.

Yes, but the point is that we do not know for sure that an xref means equivalent. If you are confident and you have other rationale beyond the xref, we should add the logical axiom to the curated file
