### ISSUE TITLE
Review classification of Orphanet_68373 in MonDO

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#91]
![image](https://cloud.githubusercontent.com/assets/6722114/15757966/1fadda12-28bd-11e6-8955-93216b47fca7.png)

Only the URIs are displayed, not the labels

http://purl.obolibrary.org/obo/OMIM_214110

**Comment by nicolevasilevsky** [comment]
@cmungall is it possible to see the labels for this one?

**Comment by cmungall** [comment]
we added these to the curated file:

```
1.0 OMIM_601539 Peroxisome Biogenesis Disorder 1B SubClassOf MESH_D052919 Refsum Disease, Infantile
1.0 OMIM_266510 Peroxisome Biogenesis Disorder 3B SubClassOf DOID_10582 Refsum disease
```

this provided a satisfiable resolution:

![img-omim_214110](https://cloud.githubusercontent.com/assets/50745/16631377/bd6d55ae-4373-11e6-885a-b530a8b2f911.png)

if it looks ok, close
