### ISSUE TITLE
Review classification of Inclusion body myositis in MonDO

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#93]
http://purl.obolibrary.org/obo/MESH_C536816

![image](https://cloud.githubusercontent.com/assets/6722114/15757946/f5de77fa-28bc-11e6-98d9-3d340ddaa068.png)

**Comment by nicolevasilevsky** [comment]
![image](https://cloud.githubusercontent.com/assets/6722114/15837777/86fd0c26-2bef-11e6-9494-00637f3904ec.png)

![image](https://cloud.githubusercontent.com/assets/6722114/15837772/83618b8c-2bef-11e6-94ce-
02e5ffe3fcd2.png)

**Comment by nicolevasilevsky** [comment]
DOI_3429 inclusion body myositis cross references Orphanet_79091, but I wonder if this synonym is wrong?

It has synonyms:
Inclusion body myopathy 2 and 
Inclusion body myopathy 3 (which is Orphanet_79091)

![image](https://cloud.githubusercontent.com/assets/6722114/15837971/94cddbfe-2bf0-11e6-8b88-daab4fb2e2d2.png)

**Comment by nicolevasilevsky** [comment]
I think these two classes are equivalent

![image](https://cloud.githubusercontent.com/assets/6722114/15838138/50e89e82-2bf1-11e6-819c-9134957762d4.png)

**Comment by nicolevasilevsky** [comment]
[Issue93.pptx](https://github.com/monarch-initiative/monarch-disease-ontology/files/301354/Issue93.pptx)

My notes.

**Comment by cmungall** [comment]
you spotted one of the major issues, and you're right about the cause:

```
[Term]
id: DOID:3429
name: inclusion body myositis
namespace: disease_ontology
def: "A myositis that is characterized by slowly progressive weakness and wasting of both distal and proximal muscles, most apparent in the muscles of the arms and legs that can occur in a sporadic or hereditary forms." [url:http://en.wikipedia.org/wiki/Inclusion_body_myositis, url:http://www.jewishgeneticdiseases.org/diseases/hereditary-inclusion-body-myopathy-2/, url:http://www.myositis.org/learn-about-myositis/types-of-myositis/inclusion-body-myositis, url:http://www.ncbi.nlm.nih.gov/gtr/conditions/C1853926/, url:http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=602]
comment: OMIM mapping confirmed by DO. [SN].
synonym: "Distal Myopathy with Rimmed Vacuoles (DMRV)" EXACT []
synonym: "Distal myopathy, Nonaka type" EXACT []
synonym: "HIBM" EXACT []
synonym: "Hereditary Inclusion Body Myopathy" EXACT []
****synonym: "IBM-3" EXACT []
****synonym: "IBM2" EXACT []
synonym: "Nonaka Myopathy" EXACT []
synonym: "Nonaka myopathy" EXACT []
****synonym: "inclusion body myopathy 2" EXACT []
****synonym: "inclusion body myopathy 3" EXACT []
```

**Comment by pnrobinson** [comment]
Just a glance at this suggests the scope/enormity of the challenge of this project, and also the incredible utility that MONDO will have if we do this right. "Hereditary Inclusion Body Myopathy" is NOT an exact-synonym of  Inclusion Body myositis, which can be sporadic or hereditary. See: 
http://emedicine.medscape.com/article/1172746-overview
We really need to get items like this correct if we want to provide a resource for precision medicine. I would suggest that we will need to manually examine the synonyms for essentially everything we import, because many of the data sources we are using have not paid attention to semantics .

**Comment by cmungall** [comment]
Just a comment on the enormity. We at least have a strategy here. The ones showing up in the tracker are ones that either kboom could not solve, or for which a solution involved selecting an OWL axiom with low prior probability. So we should be seeing the fiendish cases. This in itself is good, prior to this all of these xrefs in these resources were going relatively unexamined.

I'm hoping that there is a fair chunk for which the probabilistic approach can select the correct axiom type with high accuracy, but this awaits a full evaluation.

But either way, in a saner world we would not be doing this by piecing together existing resources in a way they weren't meant to be, we'd have more time to do things in a more formal principled manner.

**Comment by nicolevasilevsky** [comment]
@cmungall 
What are the actions needed here? Should I add the following to the curated ptable file?:

1.0 OMIM_605637 Myopathy, Proximal, and Ophthalmoplegia EquivalentTo MESH_C565311 Inclusion Body Myopathy 3, Autosomal Dominant
1.0 OMIM_147421 Inclusion Body Myositis EquivalentTo MESH_D018979 Myositis, Inclusion Body

Thanks!

**Comment by cmungall** [comment]
if you are sure of this, yes. You can also use a p<1.0
