### ISSUE TITLE
Resolve: Glaucoma

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#99]
Ordering the clusters according to ones with the most improbably priors:
- **Pr(G)**=0.3566229985443959 CONFIDENCE=0.0 Success:true
- **SIZE**=6 (3 new axioms) 
  [img](target/img-MESH_D005901.png)
- MEMBER: MESH_D005901 Glaucoma
- MEMBER: OMIA_000411 Glaucoma, generic (in other animals)
- MEMBER: DOID_9282 ocular hypertension
- MEMBER: DOID_9283 borderline glaucoma
- MEMBER: DOID_1686 glaucoma
- MEMBER: MESH_D009798 Ocular Hypertension
- OMIA_000411 Glaucoma, generic (in other animals) SubClassOf DOID_1686 glaucoma Pr= 0.9150943396226415
- **MESH_D005901 Glaucoma SubClassOf DOID_1686 glaucoma Pr= 0.14**
- DOID_9282 ocular hypertension EquivalentTo MESH_D009798 Ocular Hypertension Pr= 0.7

unlikely axiom bolded

![img-mesh_d005901](https://cloud.githubusercontent.com/assets/50745/16326596/eb9f70a2-397c-11e6-9170-143a90b2c560.png)

**Comment by cmungall** [comment]
This is a great example of the kboom technique! Can you see what's going on here?

**Comment by nicolevasilevsky** [comment]
Is the issue that in MESH, glaucoma is a subclass of Ocular hypertension and in DO, it is vice versa (ocular hypertension is a suclass of glaucoma)?

I would think that DOID_1686 and MESH_D005901 should be equiv.  And the DO 'gluacoma' cross-refs the MESH term.

**Comment by cmungall** [comment]
> Is the issue that in MESH, glaucoma is a subclass of Ocular hypertension and in DO, it is vice versa (ocular hypertension is a suclass of glaucoma)?

Yep!

> I would think that DOID_1686 and MESH_D005901 should be equiv. 

When you try that combination, every single remaining combination results in two DOIDs being mutually equivalent, and this has a prior probability setting of 0.

I think it is DO that is wrong here. This seems odd:

       is_a DOID:5679 ! retinal disease [DEF: "An eye disease that is located_in the retina."]
        is_a DOID:8466 ! retinal degeneration
         is_a DOID:1686 ! glaucoma
          is_a DOID:9283 ! borderline glaucoma
           is_a DOID:9282 ! ocular hypertension *** 

Note there is no textual defs. I can sort of see the logic,but it's problematic. 'borderline glaucoma' seems to be a temporal phase of glaucoma? Ocular hypertension can give rise to this condition? Seems to be mixing temporaral phases and causation in an unclear way

**Comment by nicolevasilevsky** [comment]
Should we file a ticket with DO?

**Comment by cmungall** [comment]
Yep!

**Comment by nicolevasilevsky** [comment]
https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/164

**Comment by nicolevasilevsky** [comment]
@cmungall should I add 
1.0 DOID:1686 glaucoma EquivalentTo MESH_D005901 to the curated-ptable file or wait for DO to fix it?

thanks!

**Comment by cmungall** [comment]
Let's go ahead and add!

**Comment by pnrobinson** [comment]
Ocular hypertension is not the same thing as glaucoma, see for instance:
http://www.aao.org/eye-health/diseases/what-is-ocular-hypertension
I am not entirely sure about the usage, but ocular hypertension seems actually to be more of a phenotypic feature, and glaucoma is a conjunction of findings related to ocular hypertension and in some cases having a defined cause. I will tryto research this, please remind me if I do not respond within a week or so.

**Comment by nicolevasilevsky** [comment]
@pnrobinson I don't think ocular hypertension is the same as glaucoma. In MESH, it is a superclass of glaucoma. I just added DOID:1686 glaucoma EquivalentTo MESH_D005901 Glaucoma

**Comment by cmungall** [comment]
@nicolevasilevsky - unfortunately that won't fix it, as there is still no combination that works without violating a hard logical link, due to the 'flip' between the two classification systems.

I can add something that allows overrides of hard links

**Comment by nicolevasilevsky** [comment]
@cmungall ah, okay. Thanks Chris!
